#!/usr/bin/env python3
"""Builds the master catalogue seed: JSON for tests, SQL for the migration.

Idempotent by construction: every insert is ON CONFLICT DO NOTHING keyed on the
product id, and ids are slugs derived from the display name exactly the way
product_search_normalize() and normalizeQuery() derive theirs. Re-running the
migration changes nothing.
"""
import json, os, re, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from data import CATALOGUE  # noqa: E402

SOURCE = "master_catalogue_v1"

# Must match normalizeQuery() in src/lib/catalog-search.ts and
# product_search_normalize() in migration 0006.
def normalize(text):
    text = text.lower().replace("'", "").replace("’", "")
    text = re.sub(r"[^a-z0-9]+", " ", text)
    return text.strip()

def slug(name):
    return normalize(name).replace(" ", "-")

def sq(value):
    return "'" + value.replace("'", "''") + "'"

products, seen_ids, collisions = [], {}, []
for (category, subcategory), block in CATALOGUE.items():
    for line in block.strip().split("\n"):
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split("|")]
        name = parts[0]
        aliases = []
        if len(parts) > 1:
            aliases = [normalize(a) for a in parts[1].split(";") if a.strip()]
        pid = slug(name)
        if not pid:
            raise SystemExit("empty id for %r" % name)
        if pid in seen_ids:
            collisions.append((pid, name, seen_ids[pid]))
            continue
        seen_ids[pid] = name
        # An alias identical to the name adds nothing to search.
        aliases = sorted({a for a in aliases if a and a != normalize(name)})
        products.append({
            "id": pid, "display_name": name, "category": category,
            "subcategory": subcategory, "search_aliases": aliases,
        })

if collisions:
    print("Dropped %d duplicate concept(s):" % len(collisions))
    for pid, name, first in collisions:
        print("  %-40s %r duplicates %r" % (pid, name, first))

pairs = sorted({(p["category"], p["subcategory"]) for p in products})
categories = sorted({c for c, _ in pairs})

root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "..")
seed_path = os.path.join(root, "supabase", "seed", "master-catalogue.json")
with open(seed_path, "w") as fh:
    json.dump({"source": SOURCE, "products": products}, fh, indent=1, ensure_ascii=False)
    fh.write("\n")


# --- Taxonomy: one source of truth for the database and the app ------------

META = {
    #                    grocery section, sort_order, kitchen walk order
    "Produce":         ("Produce",   0, 0),
    "Meat & Seafood":  ("Meat",      1, 1),
    "Dairy & Eggs":    ("Dairy",     2, 2),
    "Deli & Prepared": ("Other",     5, 3),
    "Bakery":          ("Pantry",    8, 4),
    "Pantry":          ("Pantry",    3, 5),
    "Snacks":          ("Pantry",    9, 6),
    "Confectionery":   ("Pantry",   10, 7),
    "Frozen":          ("Frozen",    4, 8),
    "Drinks":          ("Other",     6, 9),
    "Household":       ("Household", 7, None),
    "Health & Beauty": ("Household",11, None),
    "Baby & Kids":     ("Other",    12, None),
    "Pet":             ("Other",    13, None),
}

# Aisles that exist in the database with products already filed under them but
# which this seed adds nothing new to. Kept so the app never stops offering a
# home that live products already use.
EXTRA_PAIRS = [
    ("Dairy & Eggs", "Dairy"),
    ("Frozen", "Frozen Sides"),
    ("Household", "Personal Care"),
    ("Household", "Pet"),
    ("Pantry", "Bread"),
    ("Pantry", "Snacks"),
    ("Confectionery", "Fruit Snacks"),
]

by_cat = {}
for c, s_ in pairs:
    by_cat.setdefault(c, []).append(s_)

sub_rows = []
for c in categories:
    for i, s_ in enumerate(by_cat[c]):
        sub_rows.append("  (%s, %s, %d)" % (sq(c), sq(s_), i))

ui_subs = {c: list(by_cat.get(c, [])) for c in META}
for c, s_ in EXTRA_PAIRS:
    if s_ not in ui_subs[c]:
        ui_subs[c].append(s_)

ts = ['''/**
 * The canonical catalogue taxonomy — the single source of truth in code for
 * what product_categories and product_subcategories hold in the database.
 *
 * GENERATED by scripts/catalogue/build.py. Do not hand-edit: change the data
 * there and regenerate, so the code and the database cannot drift apart.
 *
 * Those are real FK-enforced tables: catalog_products.category references
 * product_categories(name), and (category, subcategory) references
 * product_subcategories. A category that isn\'t seeded cannot be used at all.
 *
 * Three parts of the app used to carry their own hardcoded copy of this list —
 * the grocery-list grouping, the pantry walk order, and the product-image icon
 * fallbacks — and a category missing from any one of them degraded silently
 * (unsorted, unranked, generic icon). One list, three consumers.
 */

export type CatalogCategory = {
  /** Matches product_categories.name exactly. */
  name: string;
  /** Section of the grocery list this files into (grocery_items.category is
   *  an older, flatter grouping fixed by a database check constraint). */
  groceryCategory: "Meat" | "Dairy" | "Produce" | "Pantry" | "Frozen" | "Household" | "Other";
  /** Mirrors product_categories.sort_order. */
  sortOrder: number;
  /** Order for the kitchen-side pantry walk (§6). Null for aisles that aren\'t
   *  stocked in the kitchen and shouldn\'t appear in that sequence. */
  kitchenOrder: number | null;
  /** Matches product_subcategories for this category. */
  subcategories: string[];
};

export const CATALOG_CATEGORIES: CatalogCategory[] = [''']

for name in sorted(META, key=lambda n: META[n][1]):
    groc, sort_order, kitchen = META[name]
    subs = ", ".join('"%s"' % x for x in ui_subs[name])
    ts.append("  {")
    ts.append('    name: "%s",' % name)
    ts.append('    groceryCategory: "%s",' % groc)
    ts.append("    sortOrder: %d," % sort_order)
    ts.append("    kitchenOrder: %s," % ("null" if kitchen is None else kitchen))
    ts.append("    subcategories: [%s]," % subs)
    ts.append("  },")

ts.append('''];

export const CATALOG_CATEGORY_NAMES: string[] = CATALOG_CATEGORIES.map((c) => c.name);

export function findCatalogCategory(name: string | null | undefined): CatalogCategory | null {
  if (!name) return null;
  return CATALOG_CATEGORIES.find((c) => c.name === name) ?? null;
}

export function isCatalogCategory(name: string): boolean {
  return findCatalogCategory(name) !== null;
}

export function subcategoriesFor(name: string): string[] {
  return findCatalogCategory(name)?.subcategories ?? [];
}

/** A (category, subcategory) pair the foreign key will accept. */
export function isCatalogSubcategory(category: string, subcategory: string): boolean {
  return subcategoriesFor(category).includes(subcategory);
}
''')

with open(os.path.join(root, "src", "lib", "catalog", "categories.ts"), "w") as fh:
    fh.write("\n".join(ts))

def grouped_values():
    assert not any("|" in p["display_name"] for p in products), "pipe in a display name"
    groups = {}
    for p in products:
        groups.setdefault((p["category"], p["subcategory"]), []).append(p["display_name"])
    return ",\n".join("  (%s, %s, %s)" % (sq(c), sq(s), sq("|".join(names)))
                      for (c, s), names in sorted(groups.items()))

def alias_values():
    return ",\n".join(
        "  (%s, array[%s])" % (sq(p["id"]), ", ".join(sq(a) for a in p["search_aliases"]))
        for p in products if p["search_aliases"])

# Aliases added to products that were ALREADY in the catalogue. Union, never
# replace: nothing the household or a receipt taught the catalogue is dropped.
EXISTING_ALIAS_ENRICHMENT = [
    ("green-onion", ["scallion", "scallions", "spring onion"]),
    ("ground-beef", ["hamburger", "minced beef"]),
    ("lean-ground-beef", ["lean hamburger"]),
    ("extra-lean-ground-beef", ["extra lean hamburger"]),
    ("boneless-skinless-chicken-breast", ["chicken breasts", "boneless chicken breast"]),
    ("bell-peppers", ["sweet pepper", "sweet peppers"]),
    ("green-bell-pepper", ["green pepper"]),
    ("red-bell-pepper", ["red pepper"]),
    ("yellow-bell-pepper", ["yellow pepper"]),
    ("ziploc-bags", ["ziploc", "zip lock bags", "resealable bags"]),
    ("aluminum-foil", ["tin foil", "foil"]),
    ("french-fries", ["fries"]),
    ("frozen-chicken-strips", ["chicken fingers", "chicken strips"]),
    ("garbage-bags", ["bin bags", "trash bags"]),
    ("popsicles", ["freezies", "ice pops"]),
    ("iceberg-lettuce", ["lettuce"]),
    ("sandwich-bread", ["bread"]),
    ("recycle-bags", ["blue box bags"]),
]

MIGRATION = '''-- HomeAssist MASTER HOUSEHOLD PRODUCT CATALOGUE
--
-- GENERATED by scripts/catalogue/build.py from scripts/catalogue/data.py.
-- Do not hand-edit: change the data there and regenerate.
--
-- A generic product VOCABULARY, not a SKU list. Every row is a household
-- product concept ("Potato Chips", "2% Milk", "Frozen French Fries") with no
-- price, package size, UPC or invented brand. Specific branded products attach
-- to these concepts later through household preferences, receipt matching and
-- retailer aliases.
--
-- Idempotent by construction. Ids are slugs the database derives from the
-- display name with the same product_search_normalize() the app's
-- normalizeQuery() mirrors, product inserts are ON CONFLICT DO NOTHING, and
-- the alias updates are scoped to rows this seed owns. Re-running changes
-- nothing. No existing row is renamed, re-filed or deleted, so the original
-- product library, the Brown Family's brand preferences (Earth's Own,
-- Lactantia, Neilson, Conestoga), learned receipt aliases and verified
-- purchase history are all untouched.

-- Aisles used by the catalogue. Existing rows are left exactly as they are.
insert into product_subcategories (category, name, sort_order) values
@@SUBS@@
on conflict (category, name) do nothing;

-- Aisles that already hold products but which this seed adds nothing to.
-- Listed so the app never stops offering a home live products already use.
insert into product_subcategories (category, name, sort_order) values
@@EXTRA@@
on conflict (category, name) do nothing;

-- The catalogue. Grouped by aisle so category and aisle appear once per group;
-- the database derives each id and normalized_name from the display name.
insert into catalog_products (id, display_name, normalized_name, category,
  subcategory, search_aliases, source, image_ready, manually_edited)
select replace(product_search_normalize(n), ' ', '-'), n,
       product_search_normalize(n), g.c, g.s, '{}'::text[], '@@SOURCE@@', false, false
from (values
@@GROUPED@@
) as g(c, s, names), unnest(string_to_array(g.names, '|')) as n
on conflict (id) do nothing;

-- Search aliases. Scoped to this seed's own rows, so a re-run cannot clobber
-- an alias a person or a receipt added to a product later.
update catalog_products p set search_aliases = v.a
from (values
@@ALIASES@@
) as v(id, a)
where p.id = v.id and p.source = '@@SOURCE@@';

-- Additive enrichment for products that predate this seed. Union, never
-- replace: an alias the household or a verified receipt already taught the
-- catalogue survives, and re-running is a no-op.
update catalog_products p
set search_aliases = (select array(select distinct unnest(p.search_aliases || v.a) order by 1))
from (values
@@ENRICH@@
) as v(id, a)
where p.id = v.id;
'''

extra_rows = ",\n".join("  (%s, %s, %d)" % (sq(c), sq(s), 90 + i)
                        for i, (c, s) in enumerate(EXTRA_PAIRS))
enrichment_rows = ",\n".join(
    "  (%s, array[%s])" % (sq(pid), ", ".join(sq(a) for a in aliases))
    for pid, aliases in EXISTING_ALIAS_ENRICHMENT)

with open(os.path.join(root, "supabase", "migrations", "0018_master_catalogue.sql"), "w") as fh:
    fh.write(
        MIGRATION.replace("@@SUBS@@", ",\n".join(sub_rows))
        .replace("@@EXTRA@@", extra_rows)
        .replace("@@GROUPED@@", grouped_values())
        .replace("@@ALIASES@@", alias_values())
        .replace("@@ENRICH@@", enrichment_rows)
        .replace("@@SOURCE@@", SOURCE))
print("migration 0018 written")
