/**
 * The canonical catalogue taxonomy — the single source of truth in code for
 * what product_categories and product_subcategories hold in the database.
 *
 * GENERATED by scripts/catalogue/build.py. Do not hand-edit: change the data
 * there and regenerate, so the code and the database cannot drift apart.
 *
 * Those are real FK-enforced tables: catalog_products.category references
 * product_categories(name), and (category, subcategory) references
 * product_subcategories. A category that isn't seeded cannot be used at all.
 *
 * Three parts of the app used to carry their own hardcoded copy of this list —
 * the grocery-list grouping, the pantry walk order, and the product-image icon
 * fallbacks — and a category missing from any one of them degraded silently
 * (unsorted, unranked, generic icon). One list, three consumers.
 */

export type CatalogCategory = {
  /** Matches product_categories.name exactly. */
  name: string;
  /** Section of the grocery list this files into (grocery_items.category is
   *  an older, flatter grouping fixed by a database check constraint). */
  groceryCategory: "Meat" | "Dairy" | "Produce" | "Pantry" | "Frozen" | "Household" | "Other";
  /** Mirrors product_categories.sort_order. */
  sortOrder: number;
  /** Order for the kitchen-side pantry walk (§6). Null for aisles that aren't
   *  stocked in the kitchen and shouldn't appear in that sequence. */
  kitchenOrder: number | null;
  /** Matches product_subcategories for this category. */
  subcategories: string[];
};

export const CATALOG_CATEGORIES: CatalogCategory[] = [
  {
    name: "Produce",
    groceryCategory: "Produce",
    sortOrder: 0,
    kitchenOrder: 0,
    subcategories: ["Fresh Herbs", "Fruit", "Leafy Greens", "Vegetables"],
  },
  {
    name: "Meat & Seafood",
    groceryCategory: "Meat",
    sortOrder: 1,
    kitchenOrder: 1,
    subcategories: ["Beef", "Pork", "Poultry", "Prepared Meat", "Seafood"],
  },
  {
    name: "Dairy & Eggs",
    groceryCategory: "Dairy",
    sortOrder: 2,
    kitchenOrder: 2,
    subcategories: ["Butter & Cream", "Cheese", "Eggs", "Milk", "Plant-Based Milk", "Yogurt", "Dairy"],
  },
  {
    name: "Pantry",
    groceryCategory: "Pantry",
    sortOrder: 3,
    kitchenOrder: 5,
    subcategories: ["Baking", "Beans & Legumes", "Breakfast", "Canned Goods", "Condiments", "Grains", "Instant Foods", "International", "Meal Kits", "Oils", "Pasta & Rice", "Sauces", "Soup & Broth", "Spices", "Bread", "Snacks"],
  },
  {
    name: "Frozen",
    groceryCategory: "Frozen",
    sortOrder: 4,
    kitchenOrder: 8,
    subcategories: ["Frozen Appetizers", "Frozen Bakery", "Frozen Breakfast", "Frozen Dessert", "Frozen Fruit", "Frozen Meals", "Frozen Meat", "Frozen Pizza", "Frozen Potatoes", "Frozen Seafood", "Frozen Vegetables", "Frozen Sides"],
  },
  {
    name: "Deli & Prepared",
    groceryCategory: "Other",
    sortOrder: 5,
    kitchenOrder: 3,
    subcategories: ["Deli", "Dips & Spreads", "Prepared Meals"],
  },
  {
    name: "Drinks",
    groceryCategory: "Other",
    sortOrder: 6,
    kitchenOrder: 9,
    subcategories: ["Coffee", "Drink Mixes", "Hot Chocolate", "Juice", "Kids Drinks", "Soft Drinks", "Sports & Energy", "Tea", "Water"],
  },
  {
    name: "Household",
    groceryCategory: "Household",
    sortOrder: 7,
    kitchenOrder: null,
    subcategories: ["Cleaning", "Cleaning Tools", "Dishwashing", "Home Supplies", "Laundry", "Paper", "Storage", "Waste", "Personal Care", "Pet"],
  },
  {
    name: "Bakery",
    groceryCategory: "Pantry",
    sortOrder: 8,
    kitchenOrder: 4,
    subcategories: ["Bagels & English Muffins", "Bread", "Buns & Rolls", "Desserts", "Sweet Baked", "Tortillas & Wraps"],
  },
  {
    name: "Snacks",
    groceryCategory: "Pantry",
    sortOrder: 9,
    kitchenOrder: 6,
    subcategories: ["Bars & Granola", "Chips", "Cookies", "Crackers", "Fruit Snacks", "Nuts & Seeds", "Popcorn & Puffs", "Rice Cakes", "Snack Mix"],
  },
  {
    name: "Confectionery",
    groceryCategory: "Pantry",
    sortOrder: 10,
    kitchenOrder: 7,
    subcategories: ["Candy", "Chocolate", "Gum & Mints", "Gummies", "Licorice", "Fruit Snacks"],
  },
  {
    name: "Health & Beauty",
    groceryCategory: "Household",
    sortOrder: 11,
    kitchenOrder: null,
    subcategories: ["Feminine Care", "Hair", "Medicine Cabinet", "Oral Care", "Personal Care", "Shaving", "Skin Care"],
  },
  {
    name: "Baby & Kids",
    groceryCategory: "Other",
    sortOrder: 12,
    kitchenOrder: null,
    subcategories: ["Baby Care", "Baby Food", "Diapers & Wipes", "Kids Snacks"],
  },
  {
    name: "Pet",
    groceryCategory: "Other",
    sortOrder: 13,
    kitchenOrder: null,
    subcategories: ["Cat", "Dog", "Pet Supplies"],
  },
];

export const CATALOG_CATEGORY_NAMES: string[] = CATALOG_CATEGORIES.map((c) => c.name);

export function findCatalogCategory(name: string | null | undefined): CatalogCategory | null {
  if (!name) return null;
  return CATALOG_CATEGORIES.find((c) => c.name === name) ?? null;
}

export function isCatalogCategory(name: string): boolean {
  return findCatalogCategory(name) !== null;
}

export function subcategoriesFor(name: string): string[] {
  return findCatalogCategory(name)?.subcategories ?? [];
}

/** A (category, subcategory) pair the foreign key will accept. */
export function isCatalogSubcategory(category: string, subcategory: string): boolean {
  return subcategoriesFor(category).includes(subcategory);
}
