-- Product photography for the catalogue.
--
-- One representative, freely-licensed photograph per generic product concept,
-- resolved from Wikipedia lead images (scripts/images/). Three checks stand
-- between a product and a picture, and all three earned their place on real
-- failures:
--   * the article's head noun must match the product and every distinguishing
--     modifier must be accounted for, so "Passion Fruit" is never illustrated
--     with the article "Fruit";
--   * the article's own description must not be about a place, person, work
--     or organisation -- "Whole Turkey" matched the article "Turkey" and
--     would otherwise have shipped the flag of a country as a photo of a bird;
--   * the article title must still share a word with the product, which is
--     what catches an article about a different food entirely.
--
-- Products that did not clear all three are simply absent: they keep the
-- category mark the app already renders, because a confident photo of the
-- wrong product is worse than an honest icon.
--
-- Licence and author come from Commons and are stored alongside, because most
-- of these are CC BY-SA and credit is a condition of use, not a courtesy.
-- Only products with no image are touched, so the hand-picked local photos
-- already in place are never overwritten.

update catalog_products p
set image_url = 'https://upload.wikimedia.org/wikipedia/commons/' || v.path,
    image_ready = true,
    image_attribution = v.attribution,
    image_license = v.license,
    image_source_url = 'https://commons.wikimedia.org/wiki/File:' || split_part(v.path, '/', 4)
from (values
  ('gala-apples','thumb/f/fb/Gala_apples_on_cloth.jpg/330px-Gala_apples_on_cloth.jpg','Nerd271','CC BY-SA 4.0'),
  ('granny-smith-apples','thumb/d/d7/Granny_smith_and_cross_section.jpg/330px-Granny_smith_and_cross_section.jpg','fir0002 flagstaffotos [at] gmail.com Canon 20D + Sigma 150mm','GFDL 1.2'),
  ('ambrosia-apples','thumb/b/be/Ambrosia_apples_2017_A2.jpg/330px-Ambrosia_apples_2017_A2.jpg','Fructibus','CC0'),
  ('bartlett-pears','thumb/0/08/Williams_Bon_Chr%C3%A9tien_1822.png/330px-Williams_Bon_Chr%C3%A9tien_1822.png','Wikimedia Commons','Public domain'),
  ('bosc-pears','thumb/e/ef/BoscPears.jpg/330px-BoscPears.jpg','User:Cacophony','CC BY 2.5'),
  ('navel-oranges','thumb/0/03/Navel_orange.jpg/330px-Navel_orange.jpg','Enoryt nwased lamaj','CC BY-SA 4.0'),
  ('mandarin-oranges','thumb/1/10/Citrus_reticulata_April_2013_Nordbaden.JPG/330px-Citrus_reticulata_April_2013_Nordbaden.JPG','4028mdk09','CC BY-SA 3.0'),
  ('canned-mandarin-oranges','thumb/1/10/Citrus_reticulata_April_2013_Nordbaden.JPG/330px-Citrus_reticulata_April_2013_Nordbaden.JPG','4028mdk09','CC BY-SA 3.0'),
  ('blackberries','thumb/7/78/Ripe%2C_ripening%2C_and_green_blackberries.jpg/330px-Ripe%2C_ripening%2C_and_green_blackberries.jpg','Ragesoss','CC BY-SA 3.0'),
  ('cranberries','thumb/3/3a/Cranberry_bog.jpg/330px-Cranberry_bog.jpg','Photo by Keith Weller','Public domain'),
  ('cherries','thumb/f/f6/Cherry_season_%2848216568227%29.jpg/330px-Cherry_season_%2848216568227%29.jpg','spurekar','CC BY 2.0'),
  ('canned-cherries','thumb/f/f6/Cherry_season_%2848216568227%29.jpg/330px-Cherry_season_%2848216568227%29.jpg','spurekar','CC BY 2.0'),
  ('frozen-cherries','thumb/f/f6/Cherry_season_%2848216568227%29.jpg/330px-Cherry_season_%2848216568227%29.jpg','spurekar','CC BY 2.0'),
  ('peaches','thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg','File:Illustration Prunus persica0.jpg: PLEASE COMPLETE AUTHO','Public domain'),
  ('canned-peaches','thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg','File:Illustration Prunus persica0.jpg: PLEASE COMPLETE AUTHO','Public domain'),
  ('frozen-peaches','thumb/9/92/Illustration_Prunus_persica_clean_no_descr.jpg/330px-Illustration_Prunus_persica_clean_no_descr.jpg','File:Illustration Prunus persica0.jpg: PLEASE COMPLETE AUTHO','Public domain'),
  ('plums','thumb/e/ec/Plums_African_Rose_-_whole%2C_halved_and_slice.jpg/330px-Plums_African_Rose_-_whole%2C_halved_and_slice.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('apricots','thumb/2/2a/Apricot_and_cross_section.jpg/330px-Apricot_and_cross_section.jpg','Fir0002','GFDL 1.2'),
  ('dried-apricots','thumb/2/2a/Apricot_and_cross_section.jpg/330px-Apricot_and_cross_section.jpg','Fir0002','GFDL 1.2'),
  ('mangoes','thumb/7/74/Mangos_-_single_and_halved.jpg/330px-Mangos_-_single_and_halved.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('dried-mango','thumb/7/74/Mangos_-_single_and_halved.jpg/330px-Mangos_-_single_and_halved.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('frozen-mango','thumb/7/74/Mangos_-_single_and_halved.jpg/330px-Mangos_-_single_and_halved.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('mango-juice','thumb/7/74/Mangos_-_single_and_halved.jpg/330px-Mangos_-_single_and_halved.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('papaya','thumb/8/84/Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg/330px-Carica_papaya_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-029.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('honeydew-melon','thumb/f/f5/Honeydew.jpg/330px-Honeydew.jpg','Yotoen','Public domain'),
  ('pomegranate-juice','thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/330px-Pomegranate_Juice_%282019%29.jpg','Augustus Binu : flickr','CC BY-SA 3.0'),
  ('figs','thumb/2/2e/Ficus_carica_L%2C_1771.jpg/330px-Ficus_carica_L%2C_1771.jpg','Trew, C.J','Public domain'),
  ('coconut','thumb/3/32/Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg/330px-Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('shredded-coconut','thumb/3/32/Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg/330px-Cocos_nucifera_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-187.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('lychee','thumb/4/46/Litchi_chinensis_fruits.JPG/330px-Litchi_chinensis_fruits.JPG','B.navez','CC BY-SA 3.0'),
  ('guava','thumb/8/88/Guava_pink_fruit.jpg/330px-Guava_pink_fruit.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('red-cabbage','thumb/8/85/Brassica_oleracea_var_capitata_Rubyball.jpg/330px-Brassica_oleracea_var_capitata_Rubyball.jpg','KENPEI','CC BY-SA 3.0'),
  ('napa-cabbage','thumb/9/95/Napa_cabbages.png/330px-Napa_cabbages.png','Bayartai','CC0'),
  ('bok-choy','thumb/9/99/Bok_Choy_%2849553125456%29.jpg/330px-Bok_Choy_%2849553125456%29.jpg','spurekar','CC BY 2.0'),
  ('leeks','thumb/6/63/Leek_on_white_background_-_0947.jpg/330px-Leek_on_white_background_-_0947.jpg','Amada44','CC BY-SA 4.0'),
  ('rutabaga','thumb/a/a7/Rutabaga%2C_variety_nadmorska.JPG/330px-Rutabaga%2C_variety_nadmorska.JPG','Picasa user Seedambassadors','CC BY-SA 3.0'),
  ('butternut-squash','thumb/7/77/Cucurbita_moschata_Butternut_2012_G2.jpg/330px-Cucurbita_moschata_Butternut_2012_G2.jpg','George Chernilevsky','Public domain'),
  ('frozen-butternut-squash','thumb/7/77/Cucurbita_moschata_Butternut_2012_G2.jpg/330px-Cucurbita_moschata_Butternut_2012_G2.jpg','George Chernilevsky','Public domain'),
  ('artichoke','thumb/6/6d/Artichoke_J1.jpg/330px-Artichoke_J1.jpg','Jamain','CC BY-SA 3.0'),
  ('artichoke-hearts','thumb/6/6d/Artichoke_J1.jpg/330px-Artichoke_J1.jpg','Jamain','CC BY-SA 3.0'),
  ('fennel','thumb/c/c0/Foeniculum_July_2011-1a.jpg/330px-Foeniculum_July_2011-1a.jpg','Alvesgaspar','CC BY-SA 3.0'),
  ('fresh-ginger','thumb/1/18/Koeh-146-no_text.jpg/330px-Koeh-146-no_text.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('mini-sweet-peppers','thumb/8/85/Green-Yellow-Red-Pepper-2009.jpg/330px-Green-Yellow-Red-Pepper-2009.jpg','Kham Tran - www.khamtran.com','CC BY-SA 3.0'),
  ('roma-tomatoes','thumb/5/52/TomateTrossRomanaTyp.jpg/330px-TomateTrossRomanaTyp.jpg','Goldlocki','CC BY-SA 3.0'),
  ('beefsteak-tomatoes','thumb/8/8e/Diversit%C3%A9_taille_tomates.jpg/330px-Diversit%C3%A9_taille_tomates.jpg','Berrucomons','CC BY-SA 3.0'),
  ('heirloom-tomatoes','thumb/4/48/Capay_heirloom_tomatoes_at_Slow_Food_Nation.jpg/330px-Capay_heirloom_tomatoes_at_Slow_Food_Nation.jpg','mercedesfromtheeighties','CC BY-SA 2.0'),
  ('pickling-cucumbers','thumb/b/bb/Pickle.jpg/330px-Pickle.jpg','Renee Comet (photographer)','Public domain'),
  ('sweet-onion','thumb/2/25/Sweet_onions_1.jpg/330px-Sweet_onions_1.jpg','Wikimedia Commons','CC BY 2.0'),
  ('kale','thumb/2/20/Boerenkool.jpg/330px-Boerenkool.jpg','Rasbak','CC BY-SA 3.0'),
  ('watercress','thumb/d/dd/Watercress_%282%29.JPG/330px-Watercress_%282%29.JPG','Masparasol','CC BY 3.0'),
  ('medium-ground-beef','thumb/d/d1/Hackfleisch-1.jpg/330px-Hackfleisch-1.jpg','No machine-readable author provided. Rainer Zenz assumed (ba','CC BY-SA 3.0'),
  ('regular-ground-beef','thumb/d/d1/Hackfleisch-1.jpg/330px-Hackfleisch-1.jpg','No machine-readable author provided. Rainer Zenz assumed (ba','CC BY-SA 3.0'),
  ('frozen-ground-beef','thumb/d/d1/Hackfleisch-1.jpg/330px-Hackfleisch-1.jpg','No machine-readable author provided. Rainer Zenz assumed (ba','CC BY-SA 3.0'),
  ('pork-ribs','thumb/2/20/Balinese_Roasted_Pork_Ribs_-_Iga_Babi_Panggang_Bali.JPG/330px-Balinese_Roasted_Pork_Ribs_-_Iga_Babi_Panggang_Bali.JPG','Gunawan Kartapranata','CC BY-SA 3.0'),
  ('bratwurst','thumb/b/b0/German_Bratw%C3%BCrste.jpg/330px-German_Bratw%C3%BCrste.jpg','Gerbis','CC BY-SA 3.0'),
  ('chorizo','thumb/2/25/Chorizos_P6021974.jpg/330px-Chorizos_P6021974.jpg','Amasuela-Luis Lafuente Agudín','CC BY-SA 4.0'),
  ('hot-dogs','thumb/b/b1/Hot_dog_with_mustard.png/330px-Hot_dog_with_mustard.png','Czar, original photographed by Renee Comet','Public domain'),
  ('veggie-burgers','thumb/e/e0/%D7%94%D7%9E%D7%91%D7%95%D7%A8%D7%92%D7%A8_%D7%98%D7%91%D7%A2%D7%95%D7%A0%D7%99.jpg/330px-%D7%94%D7%9E%D7%91%D7%95%D7%A8%D7%92%D7%A8_%D7%98%D7%91%D7%A2%D7%95%D7%A0%D7%99.jpg','Roee Shpernik','CC BY-SA 4.0'),
  ('sockeye-salmon','thumb/7/76/Sockeye_salmon_swimming_right.jpg/330px-Sockeye_salmon_swimming_right.jpg','Milton Love, Marine Science Institute, University of Califor','Public domain'),
  ('smoked-salmon','thumb/5/5d/2014_smoked_salmon_and_egg_salad_toasted_baguette.JPG/330px-2014_smoked_salmon_and_egg_salad_toasted_baguette.JPG','Takeaway','CC BY-SA 3.0'),
  ('rainbow-trout','thumb/c/c1/Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg/330px-Close_up_of_rainbow_trout_fish_underwater_oncorhynchus_mykiss.jpg','Engbretson Eric, U.S. Fish and Wildlife Service','Public domain'),
  ('mussels','thumb/4/45/CornishMussels.JPG/330px-CornishMussels.JPG','Wilson44691 at English Wikipedia','Public domain'),
  ('oysters','thumb/b/b0/Crassostrea_gigas_p1040848.jpg/330px-Crassostrea_gigas_p1040848.jpg','David Monniaux','CC BY-SA 3.0'),
  ('scallops','thumb/0/09/Argopecten_irradians.jpg/330px-Argopecten_irradians.jpg','Rachael Norris and Marina Freudzon / Mayscallop at en.wikipe','Public domain'),
  ('frozen-scallops','thumb/0/09/Argopecten_irradians.jpg/330px-Argopecten_irradians.jpg','Rachael Norris and Marina Freudzon / Mayscallop at en.wikipe','Public domain'),
  ('arctic-char','thumb/f/f2/Salvelinus_alpinus_311639131.jpg/330px-Salvelinus_alpinus_311639131.jpg','Alison Copeland','CC BY 4.0'),
  ('sliced-roast-beef','thumb/a/a3/Rostas_%28ready_and_served%29.JPG/330px-Rostas_%28ready_and_served%29.JPG','Oxiq','CC0'),
  ('salami','thumb/3/37/Salame_di_Sauris.jpg/330px-Salame_di_Sauris.jpg','Petar43','CC BY-SA 4.0'),
  ('prosciutto','thumb/1/15/Prosciutto_di_Parma%2C_ham_producing.jpg/330px-Prosciutto_di_Parma%2C_ham_producing.jpg','Udo Schröter','CC BY-SA 2.0'),
  ('meat-pie','thumb/b/b0/MeatPie.JPG/330px-MeatPie.JPG','Jonathunder','CC BY-SA 3.0'),
  ('almond-milk','thumb/d/de/Home-made_almond_milk%2C_November_2012.jpg/330px-Home-made_almond_milk%2C_November_2012.jpg','Amazing Almonds','CC BY 2.0'),
  ('oat-milk','thumb/c/c8/Oat_milk_glass_and_bottles.jpg/330px-Oat_milk_glass_and_bottles.jpg','Shisma','CC BY 4.0'),
  ('soy-milk','thumb/f/fc/004-soymilk.jpg/330px-004-soymilk.jpg','Kjokkenutstyr','CC BY-SA 2.0'),
  ('shredded-mozzarella','thumb/5/57/Mozzarella_di_bufala3.jpg/330px-Mozzarella_di_bufala3.jpg','Popo le Chien','CC BY-SA 3.0'),
  ('mozzarella-cheese','thumb/5/57/Mozzarella_di_bufala3.jpg/330px-Mozzarella_di_bufala3.jpg','Popo le Chien','CC BY-SA 3.0'),
  ('cheese-curds','thumb/4/46/Cheese_Curds_with_scale_measurement.png/330px-Cheese_Curds_with_scale_measurement.png','User:Atyndall','Public domain'),
  ('kefir','thumb/8/83/Kefir_in_a_glass.JPG/330px-Kefir_in_a_glass.JPG','Quijote at Russian Wikipedia','CC BY-SA 3.0'),
  ('margarine','thumb/5/5c/Margarine.jpg/330px-Margarine.jpg','Wikimedia Commons','CC BY-SA 2.0'),
  ('large-eggs','thumb/5/54/Adolphe_Millot_oeufs-fixed.jpg/330px-Adolphe_Millot_oeufs-fixed.jpg','Adolphe Millot','Public domain'),
  ('extra-large-eggs','thumb/5/54/Adolphe_Millot_oeufs-fixed.jpg/330px-Adolphe_Millot_oeufs-fixed.jpg','Adolphe Millot','Public domain'),
  ('free-range-eggs','thumb/7/75/FreeRangeEgg.jpg/330px-FreeRangeEgg.jpg','Wikimedia Commons','CC BY-SA 3.0'),
  ('egg-whites','thumb/4/44/Chicken_egg01_monovular.jpg/330px-Chicken_egg01_monovular.jpg','miya','CC BY 3.0'),
  ('scones','thumb/2/2a/Scone_varieties.jpg/330px-Scone_varieties.jpg','User:Dave souza','CC BY-SA 2.5'),
  ('turnovers','thumb/1/16/M%C3%B6nichwald_-_Krapfenkirtag_-_Schmerkrapfen.jpg/330px-M%C3%B6nichwald_-_Krapfenkirtag_-_Schmerkrapfen.jpg','Haeferl','CC BY-SA 3.0'),
  ('butter-tarts','thumb/3/30/ButtertartS1360020.jpg/330px-ButtertartS1360020.jpg','Alex Lozupone','CC BY-SA 4.0'),
  ('layer-cake','thumb/4/45/Rainbowcake.jpg/330px-Rainbowcake.jpg','Stephanie Astono Salim','CC BY-SA 4.0'),
  ('birthday-cake','thumb/0/06/Delicious_Birthday_Cake_%2814346969741%29.jpg/330px-Delicious_Birthday_Cake_%2814346969741%29.jpg','Jonathan Rolande from Worthing, England','CC BY 2.0'),
  ('cheesecake','thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/330px-Baked_cheesecake_with_raspberries_and_blueberries.jpg','zingyyellow','CC BY 2.0'),
  ('frozen-cheesecake','thumb/e/ea/Baked_cheesecake_with_raspberries_and_blueberries.jpg/330px-Baked_cheesecake_with_raspberries_and_blueberries.jpg','zingyyellow','CC BY 2.0'),
  ('apple-pie','thumb/e/e1/Lattice_apple_pie.png/330px-Lattice_apple_pie.png','The-Wuje','CC BY-SA 4.0'),
  ('pumpkin-pie','thumb/e/e8/Pumpkin-Pie-Whole-Slice.jpg/330px-Pumpkin-Pie-Whole-Slice.jpg','Evan-Amos','CC BY-SA 3.0'),
  ('cherry-pie','thumb/7/7e/Cherry-Pie-Slice.jpg/330px-Cherry-Pie-Slice.jpg','Evan-Amos','Public domain'),
  ('cupcakes','thumb/c/c6/Cupcakes%2C_chocolate_and_strawberry_flavour.jpg/330px-Cupcakes%2C_chocolate_and_strawberry_flavour.jpg','Marc-Lautenbacher','CC BY-SA 4.0'),
  ('trifle','thumb/4/48/Trifle_4layer.jpg/330px-Trifle_4layer.jpg','Dlublink','CC BY 3.0'),
  ('chocolate-cake','thumb/5/55/Chocolate_fudge_cake.jpg/330px-Chocolate_fudge_cake.jpg','Tracy Hunter from Kabul,, Afghanistan','CC BY 2.0'),
  ('breakfast-cereal','thumb/9/9b/NCI_Visuals_Food_Meal_Breakfast.jpg/330px-NCI_Visuals_Food_Meal_Breakfast.jpg','Unknown photographer/artist','Public domain'),
  ('raisin-bran','thumb/5/5d/Raisin-Bran-Bowl.jpg/330px-Raisin-Bran-Bowl.jpg','Evan-Amos','Public domain'),
  ('granola','thumb/9/94/Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg/330px-Granola%2C_yogurt%2C_fruit._%2816696981528%29.jpg','Arnold Gatilao from Oakland, CA, USA','CC BY 2.0'),
  ('maple-syrup','thumb/1/18/Maple_syrup.jpg/330px-Maple_syrup.jpg','User:Miguel Andrade','Public domain'),
  ('muesli','thumb/d/da/Dorset_Cereals_muesli.jpg/330px-Dorset_Cereals_muesli.jpg','Mx. Granger','CC0'),
  ('spaghetti','thumb/9/92/Spaghettoni.jpg/330px-Spaghettoni.jpg','Nnaluci','CC BY-SA 3.0'),
  ('tortellini','thumb/4/42/Tortellini_Bolognesi.jpg/330px-Tortellini_Bolognesi.jpg','Angelo.Muratore','CC BY-SA 4.0'),
  ('canned-tomatoes','thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg','Softeis','CC BY-SA 3.0'),
  ('tomatoes-on-the-vine','thumb/8/89/Tomato_je.jpg/330px-Tomato_je.jpg','Softeis','CC BY-SA 3.0'),
  ('canned-peas','thumb/1/11/Peas_in_pods_-_Studio.jpg/330px-Peas_in_pods_-_Studio.jpg','Bill Ebbesen','CC BY-SA 3.0'),
  ('frozen-peas','thumb/1/11/Peas_in_pods_-_Studio.jpg/330px-Peas_in_pods_-_Studio.jpg','Bill Ebbesen','CC BY-SA 3.0'),
  ('canned-salmon','thumb/3/39/Salmo_salar.jpg/330px-Salmo_salar.jpg','Knepp, Timothy','Public domain'),
  ('frozen-salmon','thumb/3/39/Salmo_salar.jpg/330px-Salmo_salar.jpg','Knepp, Timothy','Public domain'),
  ('canned-pineapple','thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/330px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg','Suniltg at Malayalam Wikipedia','CC BY 3.0'),
  ('frozen-pineapple','thumb/7/74/%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg/330px-%E0%B4%95%E0%B5%88%E0%B4%A4%E0%B4%9A%E0%B5%8D%E0%B4%9A%E0%B4%95%E0%B5%8D%E0%B4%95.jpg','Suniltg at Malayalam Wikipedia','CC BY 3.0'),
  ('canned-carrots','thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/330px-Vegetable-Carrot-Bundle-wStalks.jpg','Evan-Amos','Public domain'),
  ('frozen-carrots','thumb/a/a2/Vegetable-Carrot-Bundle-wStalks.jpg/330px-Vegetable-Carrot-Bundle-wStalks.jpg','Evan-Amos','Public domain'),
  ('canned-mixed-vegetables','thumb/2/24/Marketvegetables.jpg/330px-Marketvegetables.jpg','Jasper Greek Golangco','Copyrighted free use'),
  ('kidney-beans','thumb/2/27/Red_Rajma_BNC.jpg/330px-Red_Rajma_BNC.jpg','Prathyush Thomas','GFDL 1.2'),
  ('white-kidney-beans','thumb/2/27/Red_Rajma_BNC.jpg/330px-Red_Rajma_BNC.jpg','Prathyush Thomas','GFDL 1.2'),
  ('chickpeas','thumb/8/89/Chickpea_BNC.jpg/330px-Chickpea_BNC.jpg','Prathyush Thomas','GFDL 1.2'),
  ('navy-beans','thumb/9/93/Phaseolus_vulgaris_white_beans%2C_witte_boon.jpg/330px-Phaseolus_vulgaris_white_beans%2C_witte_boon.jpg','Rasbak','CC BY-SA 3.0'),
  ('pinto-beans','thumb/3/3f/Pinto_Beans_Seeds.jpg/330px-Pinto_Beans_Seeds.jpg','Sanjay Acharya','CC BY-SA 4.0'),
  ('refried-beans','thumb/5/51/Frijoles_refritos.jpg/330px-Frijoles_refritos.jpg','Karyn Christner','CC BY 2.0'),
  ('baked-beans','thumb/0/0b/Baked_beans_in_tomato_sauce.jpg/330px-Baked_beans_in_tomato_sauce.jpg','Mk2010','CC BY-SA 3.0'),
  ('green-lentils','thumb/0/03/Puy_lentils_wooden_bowl.jpg/330px-Puy_lentils_wooden_bowl.jpg','Jessica Spengler','CC BY 2.0'),
  ('split-peas','thumb/b/bc/Split_pea.jpg/330px-Split_pea.jpg','Sanjay Acharya','CC BY-SA 3.0'),
  ('mixed-beans','thumb/a/a0/French_beans_J1.JPG/330px-French_beans_J1.JPG','Jamain','CC BY-SA 3.0'),
  ('romano-beans','thumb/c/c1/Flat_beans_raw.jpg/330px-Flat_beans_raw.jpg','Andrewa','CC BY-SA 4.0'),
  ('chicken-stock','thumb/a/a9/Making_stock_for_pho_bo.jpg/330px-Making_stock_for_pho_bo.jpg','Blue Lotus','CC BY 2.0'),
  ('beef-stock','thumb/a/a9/Making_stock_for_pho_bo.jpg/330px-Making_stock_for_pho_bo.jpg','Blue Lotus','CC BY 2.0'),
  ('canned-soup','thumb/f/ff/Asparagus_soup_%28spargelsuppe%29.jpg/330px-Asparagus_soup_%28spargelsuppe%29.jpg','Petar Milošević','CC BY-SA 4.0'),
  ('chicken-noodle-soup','thumb/b/b3/Chicken_Noodle_Soup.jpg/330px-Chicken_Noodle_Soup.jpg','Hoyabird8','CC BY-SA 3.0'),
  ('tomato-soup','thumb/8/8c/Tomato_soup%2C_plant-based_%2844040252791%29.jpg/330px-Tomato_soup%2C_plant-based_%2844040252791%29.jpg','Ella Olsson from Stockholm, Sweden','CC BY 2.0'),
  ('cream-of-mushroom-soup','thumb/9/98/Cream_mushroom_soup_3.jpg/330px-Cream_mushroom_soup_3.jpg','Redeemer|Vodesnet','CC BY-SA 3.0'),
  ('vegetable-soup','thumb/7/78/Vegetable_udon_noodle_soup.jpg/330px-Vegetable_udon_noodle_soup.jpg','Jennifer','CC BY 2.0'),
  ('harissa','thumb/0/05/%D9%87%D8%B1%D9%8A%D8%B3%D8%A9_%D8%AF%D9%8A%D8%A7%D8%B1%D9%8A.JPG/330px-%D9%87%D8%B1%D9%8A%D8%B3%D8%A9_%D8%AF%D9%8A%D8%A7%D8%B1%D9%8A.JPG','Ovva olfa','CC BY-SA 4.0'),
  ('extra-virgin-olive-oil','thumb/0/0e/Oliven_V1.jpg/330px-Oliven_V1.jpg','Poyraz 72','CC BY-SA 4.0'),
  ('canola-oil','thumb/4/4b/Canola_Oil_%284107885913%29_Cropped.jpg/330px-Canola_Oil_%284107885913%29_Cropped.jpg','Veganbaking.net','CC BY-SA 2.5'),
  ('avocado-oil','thumb/a/aa/AvocadoOil.png/330px-AvocadoOil.png','Itineranttrader','Public domain'),
  ('sesame-oil','thumb/d/d9/SesameSeedOil.png/330px-SesameSeedOil.png','Itineranttrader','Public domain'),
  ('peanut-oil','thumb/0/0c/4_gallons_of_peanut_oil.jpg/330px-4_gallons_of_peanut_oil.jpg','emilee rader from Lansing, MI, USA','CC BY-SA 2.0'),
  ('apple-cider-vinegar','thumb/b/b5/Apple_Cider_Vinegar_%284108653248%29.jpg/330px-Apple_Cider_Vinegar_%284108653248%29.jpg','Veganbaking.net from USA','CC BY-SA 2.0'),
  ('balsamic-vinegar','thumb/4/4e/Balsamic_vinegar_%28drops%29.jpg/330px-Balsamic_vinegar_%28drops%29.jpg','Andrea Levers','CC BY-SA 2.0'),
  ('brown-sugar','thumb/3/3c/Sucre_blanc_cassonade_complet_rapadura.jpg/330px-Sucre_blanc_cassonade_complet_rapadura.jpg','Romain Behar','Public domain'),
  ('icing-sugar','thumb/5/5e/Powdered_Sugar_-_Macro.jpg/330px-Powdered_Sugar_-_Macro.jpg','Atm100','CC BY-SA 4.0'),
  ('baking-powder','thumb/2/2d/BakingPowder.jpg/330px-BakingPowder.jpg','Lou Sander','CC BY-SA 3.0'),
  ('vanilla-extract','thumb/0/03/VanillaExtract.png/330px-VanillaExtract.png','Itineranttrader','Public domain'),
  ('cocoa-powder','thumb/f/f3/Cocoa_press_cake.jpg/330px-Cocoa_press_cake.jpg','Chianti','CC BY-SA 3.0'),
  ('sweetened-condensed-milk','thumb/2/2f/2016-03-26-Gezuckerte_Kondensmilch-4699.jpg/330px-2016-03-26-Gezuckerte_Kondensmilch-4699.jpg','Superbass','CC BY-SA 4.0'),
  ('evaporated-milk','thumb/0/0f/Dosenmilch.jpg/330px-Dosenmilch.jpg','HV','Public domain'),
  ('molasses','thumb/8/8f/Blackstrapmolasses.JPG/330px-Blackstrapmolasses.JPG','Badagnani','CC BY 3.0'),
  ('corn-syrup','thumb/9/96/Corn_syrup.jpg/330px-Corn_syrup.jpg','Malinaccier','Public domain'),
  ('cake-mix','thumb/f/f5/Cake_mix_in_plastic_packet_photo.JPG/330px-Cake_mix_in_plastic_packet_photo.JPG','Wikimedia Commons','CC BY-SA 3.0'),
  ('croutons','thumb/e/e3/Croutons_on_a_salad.jpg/330px-Croutons_on_a_salad.jpg','Josh Truelson','CC BY-SA 2.0'),
  ('sea-salt','thumb/1/10/Salt_Farmers_-_Pak_Thale-edit1.jpg/330px-Salt_Farmers_-_Pak_Thale-edit1.jpg','JJ Harrison (jjharrison89@facebook.com) (tilt correction).','CC BY-SA 3.0'),
  ('allspice','thumb/a/a5/Pimenta_dioica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-239.jpg/330px-Pimenta_dioica_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-239.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('dried-rosemary','thumb/a/a3/Rosemary_in_bloom.JPG/330px-Rosemary_in_bloom.JPG','Margalob','CC BY-SA 4.0'),
  ('garam-masala','thumb/5/58/Garammasalaphoto.jpg/330px-Garammasalaphoto.jpg','Badagnani','CC BY 3.0'),
  ('dill-pickle-chips','thumb/9/95/Dill_pickle_chips.jpg/330px-Dill_pickle_chips.jpg','Hannah Clover','CC BY 4.0'),
  ('corn-chips','thumb/3/34/Fritos_on_a_white_background.jpg/330px-Fritos_on_a_white_background.jpg','Mx. Granger','CC0'),
  ('soda-crackers','thumb/9/9f/Saltine-Crackers.JPG/330px-Saltine-Crackers.JPG','Evan-Amos','Public domain'),
  ('cheese-crackers','thumb/a/a7/Rosemary_cheese_crackers.jpg/330px-Rosemary_cheese_crackers.jpg','Joy','CC BY 2.0'),
  ('melba-toast','thumb/f/f7/Melba_toast_tapenade.jpg/330px-Melba_toast_tapenade.jpg','Roger linders','CC BY-SA 4.0'),
  ('rice-crackers','thumb/a/ac/Arare_rice_crackers-0415.jpg/330px-Arare_rice_crackers-0415.jpg','Raimond Spekking','CC BY-SA 4.0'),
  ('cheese-puffs','thumb/4/40/No_Name_cheese_flavour_twists%2C_Canada%2C_detail_02.jpg/330px-No_Name_cheese_flavour_twists%2C_Canada%2C_detail_02.jpg','Chris Woodrich','CC BY-SA 4.0'),
  ('almonds','thumb/3/37/Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg/330px-Almonds_-_in_shell%2C_shell_cracked_open%2C_shelled%2C_blanched.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('rice-cakes','thumb/9/98/Pink_seolgitteok_cake.jpg/330px-Pink_seolgitteok_cake.jpg','Hyeon-Jeong Suk','CC BY 2.0'),
  ('mini-rice-cakes','thumb/9/98/Pink_seolgitteok_cake.jpg/330px-Pink_seolgitteok_cake.jpg','Hyeon-Jeong Suk','CC BY 2.0'),
  ('snack-mix','thumb/1/1c/Chex-Mix-Pile.jpg/330px-Chex-Mix-Pile.jpg','Evan-Amos','Public domain'),
  ('cheese-straws','thumb/7/7e/Cheese-straws-01.jpg/330px-Cheese-straws-01.jpg','gkrew','CC BY 2.0'),
  ('fruit-snacks','thumb/1/10/Welch%27s_Fruit_Snacks_%284239096810%29.jpg/330px-Welch%27s_Fruit_Snacks_%284239096810%29.jpg','sweetfixNYC','CC BY-SA 2.0'),
  ('dried-fruit','thumb/b/b2/DriedfruitS.jpg/330px-DriedfruitS.jpg','Gilabrand (talk)','CC BY 3.0'),
  ('raisins','thumb/7/7d/Raisins_01.jpg/330px-Raisins_01.jpg','Paweł Kuźniar (Jojo_1, Jojo)','CC BY-SA 3.0'),
  ('dried-cranberries','thumb/0/04/Dried-Cranberries.png/330px-Dried-Cranberries.png','Ɱ','CC BY-SA 4.0'),
  ('banana-chips','thumb/b/be/Chips_de_bananes_de_S%C3%A3o_Tom%C3%A9-et-Pr%C3%ADncipe.jpg/330px-Chips_de_bananes_de_S%C3%A3o_Tom%C3%A9-et-Pr%C3%ADncipe.jpg','Ji-Elle','CC BY-SA 4.0'),
  ('apple-chips','thumb/1/1b/Dried_Apples_%288167923741%29.jpg/330px-Dried_Apples_%288167923741%29.jpg','Leslie Seaton from Seattle, WA, USA','CC BY 2.0'),
  ('frozen-green-beans','thumb/a/a0/Heaps_of_beans.jpg/330px-Heaps_of_beans.jpg','Wikimedia Commons','GFDL 1.2'),
  ('canned-green-beans','thumb/a/a0/Heaps_of_beans.jpg/330px-Heaps_of_beans.jpg','Wikimedia Commons','GFDL 1.2'),
  ('frozen-brussels-sprouts','thumb/2/23/Brussels_sprout_closeup.jpg/330px-Brussels_sprout_closeup.jpg','Eric Hunt','CC BY 2.5'),
  ('brussels-sprouts','thumb/2/23/Brussels_sprout_closeup.jpg/330px-Brussels_sprout_closeup.jpg','Eric Hunt','CC BY 2.5'),
  ('frozen-edamame','thumb/e/e7/Edamame_by_Zesmerelda_in_Chicago.jpg/330px-Edamame_by_Zesmerelda_in_Chicago.jpg','Tammy Green (aka Zesmerelda) from Chicago Upscale Dining + L','CC BY-SA 2.0'),
  ('frozen-strawberries','thumb/4/4c/Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg/330px-Garden_strawberry_%28Fragaria_%C3%97_ananassa%29_single2.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('frozen-blueberries','thumb/1/15/Blueberries.jpg/330px-Blueberries.jpg','The original Uploader was Oven Fresh at English Wikipedia','Public domain'),
  ('dried-blueberries','thumb/1/15/Blueberries.jpg/330px-Blueberries.jpg','The original Uploader was Oven Fresh at English Wikipedia','Public domain'),
  ('frozen-mixed-fruit','thumb/3/35/Fruit_Platter-_Seasonal_Fruits.jpg/330px-Fruit_Platter-_Seasonal_Fruits.jpg','روتانا','CC BY 4.0'),
  ('frozen-bananas','thumb/f/f9/FrozenBanana.JPG/330px-FrozenBanana.JPG','Aliceofhearts','Public domain'),
  ('frozen-bacon','thumb/3/31/Made20bacon.png/330px-Made20bacon.png','Made20rder555','Public domain'),
  ('bacon','thumb/3/31/Made20bacon.png/330px-Made20bacon.png','Made20rder555','Public domain'),
  ('frozen-shrimp','thumb/b/b9/Palaemon_serratus_Croazia.jpg/330px-Palaemon_serratus_Croazia.jpg','Etrusko25','Public domain'),
  ('frozen-fish-and-chips','thumb/f/ff/Fish_and_chips_blackpool.jpg/330px-Fish_and_chips_blackpool.jpg','Matthias Meckel','CC BY-SA 4.0'),
  ('frozen-crab','thumb/7/71/Cancer_pagurus.jpg/330px-Cancer_pagurus.jpg','Hans Hillewaert','CC BY-SA 4.0'),
  ('frozen-lobster','thumb/0/0b/KreeftbijDenOsse.jpg/330px-KreeftbijDenOsse.jpg','Bart Braun','Public domain'),
  ('frozen-lasagna','thumb/b/ba/Lasagne_-_stonesoup.jpg/330px-Lasagne_-_stonesoup.jpg','jules / stonesoup','CC BY 2.0'),
  ('frozen-burrito','thumb/6/60/Burrito.JPG/330px-Burrito.JPG','samuelfernandezrivera','CC0'),
  ('frozen-pot-pie','thumb/8/80/ChickenpotpieswholeFeb09.jpg/330px-ChickenpotpieswholeFeb09.jpg','avlxyz at https://www.flickr.com/photos/avlxyz/','CC BY-SA 2.0'),
  ('frozen-shepherds-pie','thumb/5/52/Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg/330px-Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg','Oxfordian Kissuth','CC BY-SA 3.0'),
  ('shepherds-pie','thumb/5/52/Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg/330px-Homerton_College_-_Shepherd%27s_pie_%28cropped%29.jpg','Oxfordian Kissuth','CC BY-SA 3.0'),
  ('frozen-samosas','thumb/c/c4/Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg/330px-Samosas%2C_snack_food_at_Wikipedia%27s_16th_Birthday_celebration_in_Chittagong_%2801%29.jpg','Moheen Reeyad','CC BY-SA 4.0'),
  ('frozen-ravioli','thumb/9/95/Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg/330px-Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg','cyclonebill','CC BY-SA 2.0'),
  ('fresh-ravioli','thumb/9/95/Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg/330px-Flickr_-_cyclonebill_-_Ravioli_med_skinke_og_asparges_i_mascarponecreme.jpg','cyclonebill','CC BY-SA 2.0'),
  ('frozen-pancakes','thumb/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg/330px-Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg','Mae Mu','CC0'),
  ('pancake-mix','thumb/4/40/Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg/330px-Foodiesfeed.com_pouring-honey-on-pancakes-with-walnuts.jpg','Mae Mu','CC0'),
  ('frozen-yogurt','thumb/b/b8/Joghurt.jpg/330px-Joghurt.jpg','No machine-readable author provided. Rainer Zenz assumed (ba','CC BY-SA 3.0'),
  ('sorbet','thumb/3/3f/Strawberry_sorbet_zoomed.jpg/330px-Strawberry_sorbet_zoomed.jpg','star5112','CC BY-SA 2.0'),
  ('ice-pops','thumb/2/2e/Cucumber%2C_elderflower_and_mint_ice_pop_from_Nicepops_%2818159920902%29.jpg/330px-Cucumber%2C_elderflower_and_mint_ice_pop_from_Nicepops_%2818159920902%29.jpg','Ruth Hartnup from Vancouver, Canada','CC BY 2.0'),
  ('sparkling-water','5/59/Drinking_glass_00118.gif','Nevit Dilmen (talk)','CC BY-SA 3.0'),
  ('mineral-water','thumb/4/42/Vata-Gurgur.jpg/330px-Vata-Gurgur.jpg','GreatJoe at English Wikipedia','CC BY-SA 3.0'),
  ('distilled-water','thumb/c/cb/Aqua-distillata.jpg/330px-Aqua-distillata.jpg','DP-1','CC BY 2.5'),
  ('coconut-water','thumb/7/78/Young_Coconut_Drink.jpg/330px-Young_Coconut_Drink.jpg','Shameelnurani313','CC BY-SA 4.0'),
  ('tonic-water','thumb/b/b2/Tonic_water_uv.jpg/330px-Tonic_water_uv.jpg','User:Splarka from en:wp','Public domain'),
  ('flavoured-water','thumb/7/7b/I_LOHAS.jpg/330px-I_LOHAS.jpg','Tokumeigakarinoaoshima','CC BY-SA 4.0'),
  ('apple-juice','thumb/c/cf/Apfelsaft_im_Glas.jpg/330px-Apfelsaft_im_Glas.jpg','Verband der deutschen Fruchtsaftindustrie e.V.','CC BY-SA 3.0'),
  ('grape-juice','thumb/a/a5/Glass_of_grape_juice.jpeg/330px-Glass_of_grape_juice.jpeg','Oyp','CC BY-SA 3.0'),
  ('pineapple-juice','thumb/3/3b/Batido_de_pi%C3%B1a.jpg/330px-Batido_de_pi%C3%B1a.jpg','El Mono Español','CC BY-SA 4.0'),
  ('tomato-juice','thumb/3/37/Tomato_juice_316744.jpg/330px-Tomato_juice_316744.jpg','PublicDomainPictures-14','CC0'),
  ('vegetable-juice','thumb/2/28/Beet_juice-01.jpg/330px-Beet_juice-01.jpg','freshtopia.net','CC BY-SA 2.0'),
  ('lemonade','thumb/1/10/Lemonade_-_27682817724.jpg/330px-Lemonade_-_27682817724.jpg','HarshLight','CC BY 2.0'),
  ('fruit-punch','thumb/1/13/Bowle_Steinhude_2009_20090822_3.JPG/330px-Bowle_Steinhude_2009_20090822_3.JPG','Politikaner','CC BY-SA 3.0'),
  ('grapefruit-juice','thumb/a/ac/Israel_Batch_3_%282%29.JPG/330px-Israel_Batch_3_%282%29.JPG','User:Mattes','Public domain'),
  ('mason-jars','thumb/7/7e/PreservedFood1.jpg/330px-PreservedFood1.jpg','Wikimedia Commons','Public domain'),
  ('wax-paper','thumb/5/5a/Waxedpaper.jpg/330px-Waxedpaper.jpg','Kerkyra at English Wikipedia','Public domain'),
  ('matches','thumb/6/60/Friction_d%27une_allumette.jpg/330px-Friction_d%27une_allumette.jpg','Yann SEGALEN','CC BY-SA 4.0'),
  ('hair-mousse','thumb/1/17/Hair_mousse.jpg/330px-Hair_mousse.jpg','Frisko','CC BY-SA 3.0'),
  ('comb','thumb/4/4a/Plastic_comb%2C_2015-06-07.jpg/330px-Plastic_comb%2C_2015-06-07.jpg','Crisco 1492','CC BY-SA 4.0'),
  ('hair-ties','thumb/a/ad/Hair_tie.jpg/330px-Hair_tie.jpg','Eviatar Bach','CC0'),
  ('bobby-pins','thumb/f/f2/Bobby_pin.jpg/330px-Bobby_pin.jpg','Larry D. Moore','CC BY 4.0'),
  ('mouthwash','thumb/8/8f/Mouthwash_PresiDent_2023_Russia.png/330px-Mouthwash_PresiDent_2023_Russia.png','Nord794ub','CC BY-SA 4.0'),
  ('dental-floss','2/24/Floss4.jpg','oralcare','CC0'),
  ('electric-toothbrush','thumb/e/e8/Electric_toothbrush_on_a_white_background.jpg/330px-Electric_toothbrush_on_a_white_background.jpg','Curpharar','CC BY-SA 4.0'),
  ('denture-cleaner','thumb/4/4a/Overnight_Polident_Denture_Cleaner.jpg/330px-Overnight_Polident_Denture_Cleaner.jpg','Jasonbook99','CC BY-SA 3.0'),
  ('bath-bombs','thumb/5/52/Pink_cloud_rainbow_bath_bomb.webm/330px--Pink_cloud_rainbow_bath_bomb.webm.jpg','Old Mom, New Tricks','CC BY 3.0'),
  ('cotton-swabs','thumb/f/f9/White_menbo.jpg/330px-White_menbo.jpg','Aney','CC BY-SA 3.0'),
  ('nail-polish','thumb/3/38/Polished_purple_nails_with_nail_art_on.jpg/330px-Polished_purple_nails_with_nail_art_on.jpg','Köttbulleledaren','CC BY-SA 4.0'),
  ('nail-polish-remover','thumb/3/38/Polished_purple_nails_with_nail_art_on.jpg/330px-Polished_purple_nails_with_nail_art_on.jpg','Köttbulleledaren','CC BY-SA 4.0'),
  ('tweezers','thumb/d/d3/Tweezers_made_of_martensitic_stainless_steel_JIS_SUS410.jpg/330px-Tweezers_made_of_martensitic_stainless_steel_JIS_SUS410.jpg','Yapparina','CC0'),
  ('hand-sanitizer','thumb/8/8c/COVID-19_au_B%C3%A9nin_flacons_de_gel_hydroalcoolique_sur_une_table1.jpg/330px-COVID-19_au_B%C3%A9nin_flacons_de_gel_hydroalcoolique_sur_une_table1.jpg','Adoscam','CC BY-SA 4.0'),
  ('lip-balm','thumb/d/de/Homemade_lip_balm.jpg/330px-Homemade_lip_balm.jpg','Francesca Cesa Bianchi, Milano','CC BY-SA 3.0 it'),
  ('body-spray','c/c5/Axe_Bodyspray.jpg','Credits to Al Imran/Wikimedia Commons','CC BY-SA 4.0'),
  ('sunscreen','thumb/6/60/Sunscreen_on_back_under_normal_and_UV_light.jpg/330px-Sunscreen_on_back_under_normal_and_UV_light.jpg','Photograph by Andrew Steele (https://andrewsteele.co.uk), jo','CC0'),
  ('aspirin','thumb/6/6a/Acetylsalicylic_acid.jpg/330px-Acetylsalicylic_acid.jpg','Oxetane lacx','CC BY 4.0'),
  ('baby-powder','thumb/a/a5/Johnsons_Baby_Powder_1%2C5_OZS_talc%2C_pic4.JPG/330px-Johnsons_Baby_Powder_1%2C5_OZS_talc%2C_pic4.JPG','Alf van Beem','CC0'),
  ('baby-bottles','thumb/e/e1/Transparante_kunststof_zuigfles_met_blauwe_dop_en_siliconen_speen%2C_antilekplaatje_en_schroefbevestiging%2C_objectnr_83556-A-E.JPG/330px-Transparante_kunststof_zuigfles_met_blauwe_dop_en_siliconen_speen%2C_antilekplaatje_en_schroefbevestiging%2C_objectnr_83556-A-E.JPG','Museum Rotterdam','CC BY-SA 3.0'),
  ('sippy-cups','thumb/2/2a/Anywayup-Cup.jpg/330px-Anywayup-Cup.jpg','Lizf tribal','CC BY-SA 4.0'),
  ('nursing-pads','thumb/7/78/Borstcompres_Nursa.jpg/330px-Borstcompres_Nursa.jpg','Harmid','Public domain'),
  ('dog-biscuits','thumb/1/17/A_Dog_biscuit.jpg/330px-A_Dog_biscuit.jpg','germanny','CC BY-SA 2.0'),
  ('cat-litter','thumb/f/f7/Japanese_litter_box.jpg/330px-Japanese_litter_box.jpg','Ocdp','CC BY-SA 3.0'),
  ('litter-box','thumb/f/f7/Japanese_litter_box.jpg/330px-Japanese_litter_box.jpg','Ocdp','CC BY-SA 3.0'),
  ('red-delicious-apples','thumb/6/6a/Red_delicious_and_cross_section.jpg/330px-Red_delicious_and_cross_section.jpg','fir0002 flagstaffotos [at] gmail.com Canon 20D + Sigma 150mm','GFDL 1.2'),
  ('grapefruit','thumb/8/8c/Grapefruits_-_whole-halved-segments.jpg/330px-Grapefruits_-_whole-halved-segments.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('medjool-dates','thumb/1/16/%C5%9Awie%C5%BCy_daktyle_odmiany_MEDJOOL.jpg/330px-%C5%9Awie%C5%BCy_daktyle_odmiany_MEDJOOL.jpg','ORGANIChouse','CC BY-SA 4.0'),
  ('rhubarb','thumb/2/2b/Rheum_rhabarbarum.2006-04-27.uellue.jpg/330px-Rheum_rhabarbarum.2006-04-27.uellue.jpg','Dieter Weber (User:Uellue)','CC BY-SA 3.0'),
  ('parsnips','thumb/1/1f/Pastinaca_sativa_MHNT.BOT.2004.0.jpg/330px-Pastinaca_sativa_MHNT.BOT.2004.0.jpg','Didier Descouens','CC BY-SA 4.0'),
  ('acorn-squash','thumb/b/b1/Starr_070730-7820_Cucurbita_pepo.jpg/330px-Starr_070730-7820_Cucurbita_pepo.jpg','Forest & Kim Starr','CC BY 3.0'),
  ('habanero-peppers','thumb/8/86/Habanero_closeup_edit2.jpg/330px-Habanero_closeup_edit2.jpg','The original uploader was Fir0002 at English Wikipedia.','CC BY 2.5'),
  ('poblano-peppers','thumb/f/f6/Poblano_Pepper.jpg/330px-Poblano_Pepper.jpg','stef yau from Seattle, USA','CC BY 2.0'),
  ('serrano-peppers','thumb/1/15/Serranochilis.jpg/330px-Serranochilis.jpg','Cindy from Wisconsin, USA','CC BY-SA 2.0'),
  ('cauliflower-florets','thumb/2/2f/Chou-fleur_02.jpg/330px-Chou-fleur_02.jpg','Coyau','CC BY-SA 3.0'),
  ('turnip-greens','thumb/d/d3/Turnip_2622027.jpg/330px-Turnip_2622027.jpg','thebittenword.com','CC BY 2.0'),
  ('red-leaf-lettuce','thumb/b/b6/Red_leaf_lettuce_J1.JPG/330px-Red_leaf_lettuce_J1.JPG','Jamain','CC BY-SA 3.0'),
  ('coleslaw','thumb/2/29/2015-12-20_Spitzkohlsalat_mit_M%C3%B6hren_anagoria.JPG/330px-2015-12-20_Spitzkohlsalat_mit_M%C3%B6hren_anagoria.JPG','Anagoria','CC BY 3.0'),
  ('endive','thumb/0/00/Cichorium_endivia_-_Botanischer_Garten_Mainz_IMG_5453.JPG/330px-Cichorium_endivia_-_Botanischer_Garten_Mainz_IMG_5453.JPG','Oceancetaceen - Alice Chodura','CC BY-SA 3.0'),
  ('fresh-basil','thumb/9/97/Ocimum_basilicum_8zz.jpg/330px-Ocimum_basilicum_8zz.jpg','Photo by David J. Stang','CC BY-SA 4.0'),
  ('dried-basil','thumb/9/97/Ocimum_basilicum_8zz.jpg/330px-Ocimum_basilicum_8zz.jpg','Photo by David J. Stang','CC BY-SA 4.0'),
  ('fresh-parsley','thumb/e/e4/Petroselinum.jpg/330px-Petroselinum.jpg','Jonathunder','GFDL 1.2'),
  ('dried-parsley','thumb/e/e4/Petroselinum.jpg/330px-Petroselinum.jpg','Jonathunder','GFDL 1.2'),
  ('fresh-oregano','thumb/1/14/Origanum_vulgare_-_harilik_pune.jpg/330px-Origanum_vulgare_-_harilik_pune.jpg','Ivar Leidus','CC BY-SA 3.0'),
  ('dried-oregano','thumb/1/14/Origanum_vulgare_-_harilik_pune.jpg/330px-Origanum_vulgare_-_harilik_pune.jpg','Ivar Leidus','CC BY-SA 3.0'),
  ('fresh-tarragon','thumb/6/6c/Estragon_1511.jpg/330px-Estragon_1511.jpg','No machine-readable author provided. Ies assumed (based on c','Public domain'),
  ('skirt-steak','thumb/c/c2/BeefCutPlate.png/330px-BeefCutPlate.png','JoeSmack at English Wikipedia','Public domain'),
  ('beef-shank','thumb/3/33/BeefCutShank.png/330px-BeefCutShank.png','JoeSmack at en.wikipedia','Public domain'),
  ('rack-of-lamb','thumb/5/59/Rack_Carr%C3%A9_d%27agneau.JPG/330px-Rack_Carr%C3%A9_d%27agneau.JPG','User:Stephane8888 (Stephane8888 Wiktionnaire)','CC BY-SA 2.5'),
  ('leg-of-lamb','thumb/8/8c/Lamb_meat_%281%29.jpg/330px-Lamb_meat_%281%29.jpg','I would appreciate being notified if you use my work outside','CC BY-SA 3.0'),
  ('chicken-tenders','thumb/2/21/Crispy_Chicken_Strips_-_FotoosVanRobin.jpg/330px-Crispy_Chicken_Strips_-_FotoosVanRobin.jpg','FotoosVanRobin from Netherlands','CC BY-SA 2.0'),
  ('back-bacon','thumb/9/92/Bacon.JPG/330px-Bacon.JPG','Own work','Public domain'),
  ('pulled-pork','thumb/e/e5/Pulled_pork_while_pulling.JPG/330px-Pulled_pork_while_pulling.JPG','Thogru','CC BY-SA 3.0'),
  ('pork-hocks','thumb/b/b7/Schwein-Eisbein.png/330px-Schwein-Eisbein.png','User Rainer Zenz on de.wikipedia','CC BY-SA 3.0'),
  ('breakfast-sausage','thumb/e/ed/Breakfast_Sausage.jpg/330px-Breakfast_Sausage.jpg','Daniel Schwen','CC BY 3.0'),
  ('pepperoni','thumb/0/0c/Pepperoni_Pizza_%2829204589095%29.jpg/330px-Pepperoni_Pizza_%2829204589095%29.jpg','Jonathan Cutrer from San Angelo, United States','CC BY 2.0'),
  ('montreal-smoked-meat','thumb/0/02/Schwartz_smoked_meat_montreal.JPG/330px-Schwartz_smoked_meat_montreal.JPG','chensiyuan','CC BY-SA 4.0'),
  ('sushi','thumb/6/60/Sushi_platter.jpg/330px-Sushi_platter.jpg','chidorian from Japan','CC BY-SA 2.0'),
  ('quiche','thumb/2/29/Quiche.jpg/330px-Quiche.jpg','Ghouston','CC0'),
  ('mini-quiche','thumb/2/29/Quiche.jpg/330px-Quiche.jpg','Ghouston','CC0'),
  ('potato-salad','thumb/e/e9/Potato_salad_%281%29.jpg/330px-Potato_salad_%281%29.jpg','SajjadF','CC BY-SA 3.0'),
  ('hummus','thumb/b/bf/Lebanese_style_hummus.jpg/330px-Lebanese_style_hummus.jpg','Beyrouthhh at English Wikipedia','CC BY 3.0'),
  ('spinach-dip','thumb/4/48/Spinach_%26_artichoke_dip.jpg/330px-Spinach_%26_artichoke_dip.jpg','Janine from Mililani, Hawaii, United States','CC BY 2.0'),
  ('onion-dip','thumb/8/87/French_onion_dip_topped_with_caramelized_onion.jpg/330px-French_onion_dip_topped_with_caramelized_onion.jpg','Whitney in Chicago','CC BY 2.0'),
  ('whole-lactose-free-milk','thumb/4/4c/Lactose-free_milk%2C_BKK%2C_2021-10-01.jpg/330px-Lactose-free_milk%2C_BKK%2C_2021-10-01.jpg','21janvier1793','CC0'),
  ('buttermilk','thumb/2/23/Buttermilk-%28right%29-and-Milk-%28left%29.jpg/330px-Buttermilk-%28right%29-and-Milk-%28left%29.jpg','Ukko-wc','CC BY-SA 3.0'),
  ('goat-milk','thumb/a/a0/Liqueur_from_goat_milk%2C_Fuerteventura.JPG/330px-Liqueur_from_goat_milk%2C_Fuerteventura.JPG','MOs810','CC BY-SA 4.0'),
  ('coconut-milk-beverage','thumb/e/eb/Cononut_milk.JPG/330px-Cononut_milk.JPG','S Sepp','CC BY-SA 3.0'),
  ('cashew-milk','thumb/e/eb/Cononut_milk.JPG/330px-Cononut_milk.JPG','S Sepp','CC BY-SA 3.0'),
  ('canned-coconut-milk','thumb/e/eb/Cononut_milk.JPG/330px-Cononut_milk.JPG','S Sepp','CC BY-SA 3.0'),
  ('rice-milk','thumb/a/af/Rice_milk.jpg/330px-Rice_milk.jpg','Daniele Pellati','CC0'),
  ('pea-milk','thumb/8/85/Pea_protein_milk_with_yellow_split_peas.jpg/330px-Pea_protein_milk_with_yellow_split_peas.jpg','Mx. Granger','CC0'),
  ('marble-cheese','thumb/8/89/CoJack.jpg/330px-CoJack.jpg','Stephen Shep','CC BY-SA 3.0'),
  ('gouda-cheese','thumb/f/fb/Chesses_gouda_affinage.JPG/330px-Chesses_gouda_affinage.JPG','No machine-readable author provided. Alpha.prim~commonswiki ','Public domain'),
  ('brie-cheese','thumb/8/88/Brie_01.jpg/330px-Brie_01.jpg','Coyau','CC BY-SA 3.0'),
  ('camembert-cheese','thumb/d/dd/Camembert_de_Normandie_%28AOP%29_11.jpg/330px-Camembert_de_Normandie_%28AOP%29_11.jpg','Coyau','CC BY-SA 3.0'),
  ('provolone-cheese','thumb/a/a0/Provolone_watermelon_shape.jpg/330px-Provolone_watermelon_shape.jpg','like the grand canyon','CC BY 2.0'),
  ('hard-boiled-eggs','thumb/c/cc/Soft-boiled-egg.jpg/330px-Soft-boiled-egg.jpg','Amin','CC BY-SA 4.0'),
  ('whole-wheat-bread','thumb/4/46/Vegan_no-knead_whole_wheat_bread_loaf%2C_September_2010.jpg/330px-Vegan_no-knead_whole_wheat_bread_loaf%2C_September_2010.jpg','Veganbaking.net','CC BY-SA 2.0'),
  ('multigrain-bread','thumb/5/5f/Multigrain.jpg/330px-Multigrain.jpg','Jongleur100','Public domain'),
  ('rye-bread','thumb/d/d2/Market_Bread%2C_Riga%2C_Latvia.jpg/330px-Market_Bread%2C_Riga%2C_Latvia.jpg','Ken Eckert','CC BY-SA 4.0'),
  ('sourdough-bread','thumb/3/3b/Home_made_sour_dough_bread.jpg/330px-Home_made_sour_dough_bread.jpg','Tomascastelazo','CC BY-SA 4.0'),
  ('ciabatta-bread','thumb/b/b2/Ciabatta_cut.JPG/330px-Ciabatta_cut.JPG','Vincent Talleu','CC BY-SA 3.0'),
  ('naan-bread','thumb/4/4e/Annapurna_Naan.jpg/330px-Annapurna_Naan.jpg','snowpea&bokchoi','CC BY 2.0'),
  ('pita-bread','thumb/3/32/Pita_Bread.jpg/330px-Pita_Bread.jpg','Azure Dragon of the East','CC BY-SA 3.0'),
  ('focaccia','thumb/b/bf/Focaccia_with_Crumb.jpg/330px-Focaccia_with_Crumb.jpg','Fred Benenson','CC BY-SA 4.0'),
  ('raisin-bread','thumb/8/86/Cinnamon_swirl_raisin_bread.jpg/330px-Cinnamon_swirl_raisin_bread.jpg','Mendaliv','Public domain'),
  ('garlic-bread','thumb/5/59/Garlicbread.jpg/330px-Garlicbread.jpg','Popo le Chien','CC BY-SA 3.0'),
  ('frozen-garlic-bread','thumb/5/59/Garlicbread.jpg/330px-Garlicbread.jpg','Popo le Chien','CC BY-SA 3.0'),
  ('brown-bread','thumb/8/8b/Kommissbrot.jpg/330px-Kommissbrot.jpg','Benutzer:Rainer Zenz','CC BY-SA 3.0'),
  ('flatbread','thumb/c/cd/Flatbread.JPG/330px-Flatbread.JPG','Jonathunder','CC BY-SA 3.0'),
  ('hot-dog-buns','thumb/f/fb/Hotdog_-_Evan_Swigart.jpg/330px-Hotdog_-_Evan_Swigart.jpg','Evan Swigart from Chicago, USA','CC BY 2.0'),
  ('dinner-rolls','thumb/b/b8/Bread_rolls_at_a_bakery_%28cropped%29.jpg/330px-Bread_rolls_at_a_bakery_%28cropped%29.jpg','fir0002 flagstaffotos [at] gmail.com Canon 20D + Tamron 28-7','GFDL 1.2'),
  ('bagels','thumb/8/85/Bagel_with_sesame_3.jpg/330px-Bagel_with_sesame_3.jpg','Shisma','CC BY 4.0'),
  ('mini-bagels','thumb/8/85/Bagel_with_sesame_3.jpg/330px-Bagel_with_sesame_3.jpg','Shisma','CC BY 4.0'),
  ('english-muffins','thumb/e/e8/Harborview_Bistro_%26_Bar_-_January_2024_-_Sarah_Stierch_08.jpg/330px-Harborview_Bistro_%26_Bar_-_January_2024_-_Sarah_Stierch_08.jpg','Missvain','CC BY 4.0'),
  ('crumpets','thumb/3/38/Buttered_crumpet2.jpg/330px-Buttered_crumpet2.jpg','Wikimedia Commons','CC BY-SA 3.0'),
  ('flour-tortillas','thumb/5/56/NCI_flour_tortillas.jpg/330px-NCI_flour_tortillas.jpg','Wikimedia Commons','Public domain'),
  ('whole-wheat-tortillas','thumb/5/56/NCI_flour_tortillas.jpg/330px-NCI_flour_tortillas.jpg','Wikimedia Commons','Public domain'),
  ('corn-tortillas','thumb/e/ef/Mexican_tortilla.jpg/330px-Mexican_tortilla.jpg','David Boté Estrada','CC BY-SA 2.0'),
  ('taco-shells','thumb/3/3a/NCI_Visuals_Food_Taco.jpg/330px-NCI_Visuals_Food_Taco.jpg','Renee Comet (photographer)','Public domain'),
  ('muffins','thumb/4/4c/02116jfMuffins_in_Philippinesfvf_02.jpg/330px-02116jfMuffins_in_Philippinesfvf_02.jpg','Judgefloro','CC0'),
  ('muffin-mix','thumb/4/4c/02116jfMuffins_in_Philippinesfvf_02.jpg/330px-02116jfMuffins_in_Philippinesfvf_02.jpg','Judgefloro','CC0'),
  ('cake-slices','thumb/0/04/Pound_layer_cake.jpg/330px-Pound_layer_cake.jpg','Scheinwerfermann','Public domain'),
  ('carrot-cake','thumb/f/fe/Carrot_cake_at_America_Graffiti_%28cropped%29.jpg/330px-Carrot_cake_at_America_Graffiti_%28cropped%29.jpg','Elitre','CC BY-SA 4.0'),
  ('steel-cut-oats','thumb/9/9b/Bowl_of_dry_steel-cut_oats_with_full_spoon.jpeg/330px-Bowl_of_dry_steel-cut_oats_with_full_spoon.jpeg','User:Ragesoss','CC BY-SA 3.0'),
  ('breakfast-bars','thumb/c/c3/Three_protein_bars%2C_two_cut_in_half.jpg/330px-Three_protein_bars%2C_two_cut_in_half.jpg','Mx. Granger','CC0'),
  ('energy-bars','thumb/c/c3/Three_protein_bars%2C_two_cut_in_half.jpg/330px-Three_protein_bars%2C_two_cut_in_half.jpg','Mx. Granger','CC0'),
  ('penne','thumb/0/0b/Pennelisce_closeup.png/330px-Pennelisce_closeup.png','Popo le Chien','CC0'),
  ('macaroni','thumb/0/01/Macaroni2.jpg/330px-Macaroni2.jpg','Popo le Chien','CC0'),
  ('fettuccine','thumb/c/cf/Fettucine1.JPG/330px-Fettucine1.JPG','LPLT','CC BY-SA 4.0'),
  ('rigatoni','thumb/8/84/Rigatoni.jpg/330px-Rigatoni.jpg','Popo le Chien','CC0'),
  ('arborio-rice','7/79/Reis_Arborio.JPG','Wikimedia Commons','Public domain'),
  ('rice-noodles','thumb/6/6f/Rice_vermicelli.jpg/330px-Rice_vermicelli.jpg','Popo le Chien','CC BY-SA 3.0'),
  ('ramen-noodles','thumb/c/c3/Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg/330px-Shoyu_Ramen%EF%BC%88Tokyo_Ramen%EF%BC%89_-_01.jpg','Quercus acuta','CC BY-SA 4.0'),
  ('couscous','thumb/0/0c/Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg/330px-Moroccan_cuscus%2C_from_Casablanca%2C_September_2018.jpg','Lmmima','CC BY-SA 4.0'),
  ('gnocchi','thumb/8/86/Gnocchi_di_ricotta_burro_e_salvia.jpg/330px-Gnocchi_di_ricotta_burro_e_salvia.jpg','Paoletta S.','CC BY 2.0'),
  ('diced-tomatoes','thumb/c/c5/Pomidor_turshusu_e-citizen.jpg/330px-Pomidor_turshusu_e-citizen.jpg','Moonsun1981','CC BY-SA 3.0'),
  ('tomato-paste','thumb/e/e8/Tomato_paste_on_spoon.jpg/330px-Tomato_paste_on_spoon.jpg','SKopp','CC BY-SA 3.0'),
  ('canned-tomato-sauce','thumb/5/52/Fresh_Tomato_Sauce_%28Unsplash%29.jpg/330px-Fresh_Tomato_Sauce_%28Unsplash%29.jpg','Dennis Klein klein2','CC0'),
  ('canned-tuna','2/21/Tuna_assortment.png','NOAA','Public domain'),
  ('canned-sardines','thumb/a/a7/Mamakari_by_Kossy%40FINEDAYS_in_Akabane%2C_Tokyo.jpg/330px-Mamakari_by_Kossy%40FINEDAYS_in_Akabane%2C_Tokyo.jpg','Kossy@FINEDAYS from Izakaya Marumasu-Ya in Akabane, Kita, To','CC BY 2.0'),
  ('canned-pumpkin','thumb/5/5c/FrenchMarketPumpkinsB.jpg/330px-FrenchMarketPumpkinsB.jpg','Infrogmation of New Orleans','CC BY-SA 3.0'),
  ('minestrone-soup','thumb/f/fe/Minestrone_soup_%285%29.jpg/330px-Minestrone_soup_%285%29.jpg','Daniel Ziegener','CC BY-SA 2.0'),
  ('bouillon-cubes','thumb/f/f5/Br%C3%BChw%C3%BCrfel-1.jpg/330px-Br%C3%BChw%C3%BCrfel-1.jpg','Rainer Z ...','CC BY-SA 3.0'),
  ('chowder','thumb/b/b8/Shrimp_and_corn_chowder.jpg/330px-Shrimp_and_corn_chowder.jpg','Leszek Leszczynski','CC BY 2.0'),
  ('pearl-barley','thumb/3/32/Barley_grains.jpg/330px-Barley_grains.jpg','국립국어원','CC BY-SA 2.0 kr'),
  ('curry-paste','thumb/8/80/Patak%27s_sauces_for_sale_in_Asda.jpg/330px-Patak%27s_sauces_for_sale_in_Asda.jpg','Victuallers','CC BY-SA 3.0'),
  ('fish-sauce','thumb/b/b0/Sauce_de_poisson.jpg/330px-Sauce_de_poisson.jpg','Assassas77','CC BY-SA 4.0'),
  ('gochujang','thumb/c/cb/Korean_chili_pepper_paste_GOCHUJANG.jpg/330px-Korean_chili_pepper_paste_GOCHUJANG.jpg','Korea Agro-Fisheries & Food Trade Corporation','KOGL Type 1'),
  ('wasabi-paste','thumb/5/53/Wasabia_japonica_4.JPG/330px-Wasabia_japonica_4.JPG','Qwert1234','CC BY-SA 3.0'),
  ('kimchi','thumb/f/f8/Various_kimchi.jpg/330px-Various_kimchi.jpg','국립국어원','CC BY-SA 2.0 kr'),
  ('tempeh','thumb/e/e1/Tempeh_%288681605421%29.jpg/330px-Tempeh_%288681605421%29.jpg','Veganbaking.net from USA','CC BY-SA 2.0'),
  ('masa-harina','thumb/3/3b/Masa_de_tortillas.jpg/330px-Masa_de_tortillas.jpg','Artemisa Martínez','CC0'),
  ('instant-noodles','thumb/7/73/Mama_instant_noodle_block.jpg/330px-Mama_instant_noodle_block.jpg','Takeaway','CC BY-SA 3.0'),
  ('boxed-mac-and-cheese','thumb/4/44/Original_Mac_n_Cheese_.jpg/330px-Original_Mac_n_Cheese_.jpg','Texasfoodgawker','CC BY-SA 4.0'),
  ('frozen-mac-and-cheese','thumb/4/44/Original_Mac_n_Cheese_.jpg/330px-Original_Mac_n_Cheese_.jpg','Texasfoodgawker','CC BY-SA 4.0'),
  ('boxed-stuffing','thumb/a/ae/Stuffing_a_turkey.jpg/330px-Stuffing_a_turkey.jpg','Rick Kimpel','CC BY-SA 2.0'),
  ('canned-pasta','thumb/3/3f/%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg/330px-%28Pasta%29_by_David_Adam_Kess_%28pic.2%29.jpg','David Adam Kess','CC BY-SA 4.0'),
  ('instant-pudding','thumb/4/43/Instant_pudding_mix_and_milk.jpg/330px-Instant_pudding_mix_and_milk.jpg','Amy Stephenson','CC BY-SA 2.0'),
  ('enchilada-sauce','thumb/e/ec/Enchilada_Rice_Beans.jpg/330px-Enchilada_Rice_Beans.jpg','Jon Sullivan','Public domain'),
  ('teriyaki-sauce','thumb/9/91/22nd_June_2012_Teriyaki_Duck.jpg/330px-22nd_June_2012_Teriyaki_Duck.jpg','Murcotipton','CC BY-SA 3.0'),
  ('tartar-sauce','thumb/1/19/Tartar_Sauce.jpg/330px-Tartar_Sauce.jpg','jeffreyw','CC BY 2.0'),
  ('plum-sauce','thumb/1/19/Plumjf.JPG/330px-Plumjf.JPG','Ramon FVelasquez','CC BY-SA 3.0'),
  ('thousand-island-dressing','thumb/f/fa/Thousand-Island-Dressing.jpg/330px-Thousand-Island-Dressing.jpg','Rainer Z ...','CC BY-SA 3.0'),
  ('honey','thumb/c/cc/Runny_hunny.jpg/330px-Runny_hunny.jpg','Scott Bauer, USDA ARS','Public domain'),
  ('marmalade','thumb/3/30/Homemade_marmalade%2C_England.jpg/330px-Homemade_marmalade%2C_England.jpg','Amanda Slater','CC BY-SA 2.0'),
  ('strawberry-jam','thumb/4/43/Strawberry_jam_%28home_preservation%29.jpg/330px-Strawberry_jam_%28home_preservation%29.jpg','Nutrition, Food Safety & Health','CC0'),
  ('aioli','thumb/4/43/A%C3%AFoli_maison.jpg/330px-A%C3%AFoli_maison.jpg','Marianne Casamance','CC BY-SA 4.0'),
  ('maple-butter','thumb/6/62/Maple_butter.jpg/330px-Maple_butter.jpg','Gail from Calgary, Canada','CC BY 2.0'),
  ('sunflower-seed-butter','thumb/6/6c/Tj%27s_sunflower_butter.JPG/330px-Tj%27s_sunflower_butter.JPG','Monroe87','CC BY-SA 4.0'),
  ('vinaigrette','thumb/9/98/Vinaigrette_dressing_with_a_chopped_salad.jpg/330px-Vinaigrette_dressing_with_a_chopped_salad.jpg','GrammarFascist','CC BY-SA 4.0'),
  ('coconut-oil','thumb/f/f3/Coconut_and_oil.jpg/330px-Coconut_and_oil.jpg','Phu Thinh Co','CC BY-SA 2.0'),
  ('pizza-dough','thumb/9/91/Pizza-3007395.jpg/330px-Pizza-3007395.jpg','igorovsyannykov','CC0'),
  ('frozen-pizza-crust','thumb/9/91/Pizza-3007395.jpg/330px-Pizza-3007395.jpg','igorovsyannykov','CC0'),
  ('gelatin','thumb/3/3f/Gelatine.png/330px-Gelatine.png','Danielle dk','CC BY-SA 3.0'),
  ('marshmallows','thumb/3/3d/White_Marshmallows.jpg/330px-White_Marshmallows.jpg','John Morgan','CC BY 2.0'),
  ('oat-flour','thumb/f/f0/AvenaSativa3.jpg/330px-AvenaSativa3.jpg','Christian Fischer','CC BY-SA 4.0'),
  ('pie-filling','thumb/a/a6/Top_down_view_of_peach_pie_%28722379748%29.jpg/330px-Top_down_view_of_peach_pie_%28722379748%29.jpg','Heather from Maine, USA','CC BY 2.0'),
  ('frozen-pie','thumb/a/a6/Top_down_view_of_peach_pie_%28722379748%29.jpg/330px-Top_down_view_of_peach_pie_%28722379748%29.jpg','Heather from Maine, USA','CC BY 2.0'),
  ('kosher-salt','thumb/0/07/Comparison_of_Table_Salt_with_Kitchen_Salt.png/330px-Comparison_of_Table_Salt_with_Kitchen_Salt.png','Lexlex','CC BY-SA 4.0'),
  ('black-pepper','thumb/f/fd/Piper_nigrum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-107.jpg/330px-Piper_nigrum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-107.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('garlic-powder','thumb/2/26/Ground-Garlic_31534-480x360_%284904476773%29.jpg/330px-Ground-Garlic_31534-480x360_%284904476773%29.jpg','Emilian Robert Vicol from Com. Balanesti, Romania','CC BY 2.0'),
  ('onion-powder','thumb/3/36/Onion_Powder%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg/330px-Onion_Powder%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg','John Phelan','CC BY-SA 3.0'),
  ('paprika','8/81/Piment%C3%B3n_Tap_de_Cort%C3%AD_%28cropped%29.jpg','Marcosgarrido88','CC BY-SA 3.0'),
  ('turmeric','thumb/a/ab/Turmeric_inflorescence.jpg/330px-Turmeric_inflorescence.jpg','SKsiddhartthan','CC BY-SA 4.0'),
  ('curry-powder','thumb/6/60/Curry_powder_in_the_spice-bazaar_in_Istanbul.jpg/330px-Curry_powder_in_the_spice-bazaar_in_Istanbul.jpg','Thomas Steiner','CC BY-SA 3.0'),
  ('cayenne-pepper','thumb/d/d2/Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg/330px-Capsicum_annuum_-_K%C3%B6hler%E2%80%93s_Medizinal-Pflanzen-027.jpg','Franz Eugen Köhler, Köhler''s Medizinal-Pflanzen','Public domain'),
  ('crushed-red-pepper','thumb/3/32/2014_Dried_chilli_flakes.jpg/330px-2014_Dried_chilli_flakes.jpg','Takeaway','CC BY-SA 4.0'),
  ('dried-thyme','thumb/e/ea/Thyme-Bundle.jpg/330px-Thyme-Bundle.jpg','Evan-Amos','CC0'),
  ('dill-weed','thumb/4/4b/Illustration_Anethum_graveolens_clean.jpg/330px-Illustration_Anethum_graveolens_clean.jpg','Illustration_Anethum_graveolens0.jpg: Prof. Dr. Otto Wilhelm','Public domain'),
  ('italian-seasoning','thumb/3/33/Italian_Herb_Mix%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg/330px-Italian_Herb_Mix%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg','John Phelan','CC BY-SA 3.0'),
  ('herbes-de-provence','thumb/1/1b/Herbes_de_Provence_02.jpg/330px-Herbes_de_Provence_02.jpg','Arnaud 25','CC BY-SA 4.0'),
  ('lemon-pepper','thumb/e/e9/Homemade_lemon_pepper.jpg/330px-Homemade_lemon_pepper.jpg','krzysiu.net (Krzysztof Blachnicki)','CC BY 4.0'),
  ('garlic-salt','thumb/6/66/GarlicSalt.jpg/330px-GarlicSalt.jpg','Tmcfulton','Public domain'),
  ('seasoning-salt','thumb/d/d8/Seasoned_Salt%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg/330px-Seasoned_Salt%2C_Penzeys_Spices%2C_Arlington_Heights_MA.jpg','John Phelan','CC BY-SA 3.0'),
  ('chinese-five-spice','thumb/b/b3/Five_spice_powder.jpg/330px-Five_spice_powder.jpg','w:en:User:Leadehua','Public domain'),
  ('vanilla-bean','thumb/0/0f/Vanilla_planifolia_%286998639597%29.jpg/330px-Vanilla_planifolia_%286998639597%29.jpg','Malcolm Manners from Lakeland FL, USA','CC BY 2.0'),
  ('potato-chips','thumb/6/69/Potato-Chips.jpg/330px-Potato-Chips.jpg','Evan-Amos','Public domain'),
  ('ketchup-chips','thumb/b/b6/Ketchup_chips.jpg/330px-Ketchup_chips.jpg','Hannah Clover','CC BY 4.0'),
  ('veggie-chips','thumb/c/ca/Deep_Fried_Cassava_Chips.jpg/330px-Deep_Fried_Cassava_Chips.jpg','Cmumbe','CC BY-SA 4.0'),
  ('graham-crackers','thumb/8/87/Graham-Cracker-Stack.jpg/330px-Graham-Cracker-Stack.jpg','Evan-Amos','Public domain'),
  ('popcorn','thumb/d/d6/Popcorn_-_Studio_-_2011.jpg/330px-Popcorn_-_Studio_-_2011.jpg','Bill Ebbesen','CC BY-SA 3.0'),
  ('microwave-popcorn','thumb/1/1d/Popcorn_bag_unpopped.jpg/330px-Popcorn_bag_unpopped.jpg','Holly Cheng','CC BY-SA 3.0'),
  ('kettle-corn','thumb/5/54/Kettle_Corn.jpg/330px-Kettle_Corn.jpg','msgohan','Public domain'),
  ('pretzels','thumb/3/30/BrezelnSalz02_%28cropped%29.JPG/330px-BrezelnSalz02_%28cropped%29.JPG','Sundar1','CC BY-SA 3.0'),
  ('macadamia-nuts','thumb/9/96/Macadamia_nuts_on_tree.JPG/330px-Macadamia_nuts_on_tree.JPG','MorePix','CC BY-SA 3.0'),
  ('brazil-nuts','thumb/3/39/Bertholletia_excelsa_compose.jpg/330px-Bertholletia_excelsa_compose.jpg','Lior Golgher (upper left photo and upper middle photo), U.S.','CC BY-SA 4.0'),
  ('mixed-nuts','thumb/f/f5/Mixed_nuts_small_white1.jpg/330px-Mixed_nuts_small_white1.jpg','User:Melchoir','CC BY-SA 3.0'),
  ('sunflower-seeds','thumb/3/39/Sunflower_Seeds_Kaldari.jpg/330px-Sunflower_Seeds_Kaldari.jpg','Kaldari','Public domain'),
  ('trail-mix','thumb/f/fd/2021-05-15_04_45_03_A_sample_of_Kirkland_Trail_Mix_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg/330px-2021-05-15_04_45_03_A_sample_of_Kirkland_Trail_Mix_in_the_Dulles_section_of_Sterling%2C_Loudoun_County%2C_Virginia.jpg','Famartin','CC BY-SA 4.0'),
  ('protein-bars','thumb/5/55/Three_protein_bars.jpg/330px-Three_protein_bars.jpg','Mx. Granger','CC0'),
  ('oat-bars','thumb/7/74/Flapjacks.jpg/330px-Flapjacks.jpg','Alistair young','CC BY 2.0'),
  ('chocolate-truffles','thumb/7/7f/Truffles_with_nuts_and_chocolate_dusting_in_detail.jpg/330px-Truffles_with_nuts_and_chocolate_dusting_in_detail.jpg','David Leggett','CC BY 2.0'),
  ('boxed-chocolates','thumb/1/11/Three_Bars_%281%29.jpg/330px-Three_Bars_%281%29.jpg','Lynnereal','CC BY-SA 4.0'),
  ('chocolate-eggs','thumb/1/11/Three_Bars_%281%29.jpg/330px-Three_Bars_%281%29.jpg','Lynnereal','CC BY-SA 4.0'),
  ('chocolate-coins','thumb/8/81/Chocolatemoney2.jpg/330px-Chocolatemoney2.jpg','ritcharnd moskow from Toshi Station, USA','CC BY-SA 2.0'),
  ('peanut-butter-cups','thumb/b/bd/Reese%27s_peanut_butter_cups.jpg/330px-Reese%27s_peanut_butter_cups.jpg','Gila Brand, aka Gilabrand at en.wikipedia','CC BY 3.0'),
  ('hard-candy','thumb/1/13/HardCandy.jpg/330px-HardCandy.jpg','Adam Zivner','CC BY-SA 3.0'),
  ('caramels','thumb/8/89/Caramel-2.jpg/330px-Caramel-2.jpg','No machine-readable author provided. Rainer Zenz assumed (ba','CC BY-SA 3.0'),
  ('toffee','thumb/f/f3/Thorntonstoffee.jpg/330px-Thorntonstoffee.jpg','Stratford490','CC BY-SA 3.0'),
  ('gummy-bears','thumb/a/a6/Oursons_g%C3%A9latine_march%C3%A9_Rouffignac.jpg/330px-Oursons_g%C3%A9latine_march%C3%A9_Rouffignac.jpg','Jebulon','CC0'),
  ('gummy-worms','thumb/e/e1/Three_Nice%21_Gummy_Worms_%2819543065510%29.jpg/330px-Three_Nice%21_Gummy_Worms_%2819543065510%29.jpg','Willis Lam','CC BY-SA 2.0'),
  ('wine-gums','thumb/0/09/Maynards-Wine-Gums.jpg/330px-Maynards-Wine-Gums.jpg','Evan-Amos','CC0'),
  ('jujubes','thumb/5/54/Ferrara-Candy-Jujubes.jpg/330px-Ferrara-Candy-Jujubes.jpg','Evan-Amos','Public domain'),
  ('licorice-allsorts','thumb/b/ba/Liquorice_Allsorts_in_a_glass_bowl.jpg/330px-Liquorice_Allsorts_in_a_glass_bowl.jpg','David Edgar','CC BY-SA 4.0'),
  ('chewing-gum','thumb/9/9d/Chewing_gum_stick.jpg/330px-Chewing_gum_stick.jpg','Lusheeta','CC BY-SA 3.0'),
  ('mints','thumb/c/c1/Scotch_mints.JPG/330px-Scotch_mints.JPG','Themightyquill','CC BY-SA 3.0'),
  ('peppermints','thumb/7/72/Pfefferminze_natur_peppermint.jpg/330px-Pfefferminze_natur_peppermint.jpg','Own work','CC BY 3.0'),
  ('frozen-raspberries','thumb/a/a7/Raspberry_-_halved_%28Rubus_idaeus%29.jpg/330px-Raspberry_-_halved_%28Rubus_idaeus%29.jpg','Ivar Leidus','CC BY-SA 4.0'),
  ('frozen-french-fries','thumb/8/83/French_Fries.JPG/330px-French_Fries.JPG','StockSnap','CC0'),
  ('onion-rings','thumb/e/eb/OnionRings.JPG/330px-OnionRings.JPG','Jonathunder','CC BY-SA 3.0'),
  ('hawaiian-frozen-pizza','thumb/e/ea/Pizza_with_pineapple.jpg/330px-Pizza_with_pineapple.jpg','Janine from Mililani, Hawaii, United States','CC BY 2.0'),
  ('chicken-nuggets','thumb/6/64/Chicken_Nuggets.jpg/330px-Chicken_Nuggets.jpg','James Palinsad','CC BY-SA 2.0'),
  ('popcorn-chicken','thumb/6/6c/KFC_Popcorn_Chicken_%2812956064765%29.jpg/330px-KFC_Popcorn_Chicken_%2812956064765%29.jpg','Mike Mozart from Funny YouTube, USA','CC BY 2.0'),
  ('frozen-sausages','thumb/2/29/Wurstplatte.jpg/330px-Wurstplatte.jpg','Alice Wiegand','CC BY-SA 4.0'),
  ('mozzarella-sticks','thumb/6/6f/Fried_Mozzarella_Sticks_at_Millers_Pub_%28301456962%29.jpg/330px-Fried_Mozzarella_Sticks_at_Millers_Pub_%28301456962%29.jpg','Kim Scarborough from Chicago, IL','CC BY-SA 2.0'),
  ('frozen-egg-rolls','thumb/f/fd/CookbookEggrollTongs.jpg/330px-CookbookEggrollTongs.jpg','Wikimedia Commons','Public domain'),
  ('frozen-potato-skins','thumb/d/dc/Potato_skins_arranged_on_a_plate_as_an_appetizer.jpg/330px-Potato_skins_arranged_on_a_plate_as_an_appetizer.jpg','don_naked','CC BY-SA 2.0'),
  ('frozen-bruschetta','thumb/1/1f/2014_Bruschetta_The_Larder_Chiang_Mai.jpg/330px-2014_Bruschetta_The_Larder_Chiang_Mai.jpg','Takeaway','CC BY-SA 4.0'),
  ('frozen-waffles','thumb/5/5b/Waffles_with_Strawberries.jpg/330px-Waffles_with_Strawberries.jpg','Parkerman & Christie from San Diego, USA','CC BY 2.0'),
  ('breakfast-sandwiches','thumb/9/9d/Breakfast_sandwich.jpg/330px-Breakfast_sandwich.jpg','jeffreyw','CC BY 2.0'),
  ('frozen-croissants','thumb/2/2a/Croissant-Petr_Kratochvil.jpg/330px-Croissant-Petr_Kratochvil.jpg','Petr Kratochvil','CC0'),
  ('frozen-cookie-dough','thumb/8/81/Cookiedough.jpg/330px-Cookiedough.jpg','Geraldine','CC BY 2.0'),
  ('vanilla-ice-cream','thumb/f/f3/Vanilla_Ice_Cream_Cone_at_Camp_Manitoulin.jpg/330px-Vanilla_Ice_Cream_Cone_at_Camp_Manitoulin.jpg','Steven Depolo','CC BY 2.0'),
  ('ice-cream-bars','thumb/6/62/2020-03-29_20_25_48_A_partially_eaten_H%C3%A4agen-Dazs_Vanilla_Milk_Chocolate_Almond_Ice_Cream_Bar_in_the_Franklin_Farm_section_of_Oak_Hill%2C_Fairfax_County%2C_Virginia.jpg/330px-thumbnail.jpg','Famartin','CC BY-SA 4.0'),
  ('ice-cream-cones','thumb/d/da/Strawberry_ice_cream_cone_%285076899310%29.jpg/330px-Strawberry_ice_cream_cone_%285076899310%29.jpg','TheCulinaryGeek from Chicago, USA','CC BY 2.0'),
  ('ice-cream-cake','thumb/a/a0/Ice_Cream_swiss_roll.jpg/330px-Ice_Cream_swiss_roll.jpg','raisin bun','CC BY-SA 2.0'),
  ('club-soda','thumb/3/35/President%27s_Choice_Club_Soda.jpg/330px-President%27s_Choice_Club_Soda.jpg','Diclements','CC BY-SA 3.0'),
  ('cranberry-juice','thumb/5/59/Cranberry_juice_in_a_cup.jpg/330px-Cranberry_juice_in_a_cup.jpg','Lisa Pinehill','CC BY-SA 2.0'),
  ('limeade','thumb/2/2b/Limeade.jpg/330px-Limeade.jpg','Michael Fludkov','CC BY 2.0'),
  ('smoothie','thumb/0/0c/Kiwi_Smoothie.jpg/330px-Kiwi_Smoothie.jpg','rawpixel.com','CC0'),
  ('apple-cider','thumb/6/60/Cider_and_apple_juice.jpg/330px-Cider_and_apple_juice.jpg','Wikimedia Commons','CC BY-SA 3.0'),
  ('cola','thumb/2/23/Glass_of_Cola.jpg/330px-Glass_of_Cola.jpg','Cocktailmarler','CC BY-SA 4.0'),
  ('soda-cans','thumb/f/ff/Drinking_can_ring-pull_tab.jpg/330px-Drinking_can_ring-pull_tab.jpg','Marcos André','CC BY 2.0'),
  ('sports-drink','thumb/f/ff/Gatorade_185838.jpg/330px-Gatorade_185838.jpg','SecretName101','CC BY-SA 4.0'),
  ('electrolyte-drink','thumb/f/ff/Gatorade_185838.jpg/330px-Gatorade_185838.jpg','SecretName101','CC BY-SA 4.0'),
  ('energy-drink','thumb/7/77/Energydrinks.jpg/330px-Energydrinks.jpg','AlienFood','CC BY-SA 4.0'),
  ('black-tea','thumb/8/8a/Cup_of_black_tea.JPG/330px-Cup_of_black_tea.JPG','AntanO','CC BY-SA 4.0'),
  ('green-tea','thumb/3/36/Green_tea_3_appearances.jpg/330px-Green_tea_3_appearances.jpg','Alessandro Martini','CC0'),
  ('herbal-tea','thumb/5/56/Hibiscus_Delight_tisane.jpg/330px-Hibiscus_Delight_tisane.jpg','Violette79 from Brooklyn, NY, USA','CC BY 2.0'),
  ('chamomile-tea','thumb/2/26/Kamomillasaunio_%28Matricaria_recutita%29.JPG/330px-Kamomillasaunio_%28Matricaria_recutita%29.JPG','kallerna','CC BY-SA 3.0'),
  ('earl-grey-tea','thumb/d/d0/Frisch_aufgebr%C3%BChter_EarlGrey_Tee.jpg/330px-Frisch_aufgebr%C3%BChter_EarlGrey_Tee.jpg','soultea.de/André Helbig','CC BY-SA 3.0'),
  ('english-breakfast-tea','thumb/4/4e/Mug_of_English_Breakfast_Tea.jpg/330px-Mug_of_English_Breakfast_Tea.jpg','Lisaisanut','CC0'),
  ('tea-bags','thumb/8/80/Tea_bags.jpg/330px-Tea_bags.jpg','André Karwath aka Aka','CC BY-SA 2.5'),
  ('sweet-tea','thumb/e/ef/Iced_Tea_from_flickr.jpg/330px-Iced_Tea_from_flickr.jpg','Melissa Doroquez','CC BY-SA 2.0'),
  ('ground-coffee','thumb/a/a8/TEDxAMS2011_044.JPG/330px-TEDxAMS2011_044.JPG','Vera de Kok','CC BY-SA 3.0'),
  ('flavoured-coffee','thumb/a/a8/TEDxAMS2011_044.JPG/330px-TEDxAMS2011_044.JPG','Vera de Kok','CC BY-SA 3.0'),
  ('facial-tissue','thumb/e/eb/Box_of_Scotties_tissues.jpg/330px-Box_of_Scotties_tissues.jpg','Wikimedia Commons','CC BY-SA 3.0'),
  ('napkins','thumb/5/53/Napkin_ring.jpg/330px-Napkin_ring.jpg','Neeta Lind','CC BY 2.0'),
  ('paper-cups','thumb/c/c2/Paper_cup_DS.jpg/330px-Paper_cup_DS.jpg','Augustus Binu : flickr','CC BY-SA 3.0'),
  ('mop','thumb/4/4c/Mop%2C_three_different_mop_handles.jpg/330px-Mop%2C_three_different_mop_handles.jpg','Bjornwireen','Public domain'),
  ('broom','thumb/b/b0/BroomsforSale.jpg/330px-BroomsforSale.jpg','Edal Anton Lefterov','CC BY-SA 3.0'),
  ('dustpan','thumb/a/ac/Stofferenblik.jpg/330px-Stofferenblik.jpg','M.Minderhoud','CC BY-SA 3.0'),
  ('toilet-brush','thumb/5/58/Klobuersten_%28fcm%29.jpg/330px-Klobuersten_%28fcm%29.jpg','Photograph: Frank C. Müller, Baden-Baden','CC BY-SA 4.0'),
  ('squeegee','thumb/e/e5/2005_squeegee_sponge_chalk.jpg/330px-2005_squeegee_sponge_chalk.jpg','No machine-readable author provided. Rl assumed (based on co','CC BY-SA 3.0'),
  ('steel-wool','thumb/8/8d/Steel-wool.jpg/330px-Steel-wool.jpg','Johan','CC BY-SA 3.0'),
  ('nasal-spray','thumb/a/a7/Action_photo_of_nasal_spray_on_a_black_background.jpg/330px-Action_photo_of_nasal_spray_on_a_black_background.jpg','robin_24','CC BY 2.0'),
  ('dishwasher-detergent','thumb/2/24/Detergent_tablet.jpg/330px-Detergent_tablet.jpg','Daniel78','CC BY-SA 3.0'),
  ('extension-cord','thumb/8/8c/Extension_cord.JPG/330px-Extension_cord.JPG','Taylor Cedarmas','CC BY-SA 3.0'),
  ('duct-tape','thumb/8/89/Duct-tape.jpg/330px-Duct-tape.jpg','Evan-Amos','Public domain'),
  ('masking-tape','thumb/f/f4/Malerkrepp.jpg/330px-Malerkrepp.jpg','Neitram','CC BY-SA 3.0'),
  ('lighters','thumb/c/c9/White_lighter_with_flame.JPG/330px-White_lighter_with_flame.JPG','Kimmo Palosaari','Public domain'),
  ('candles','thumb/a/aa/LA2_Skultuna_kontorsljusstake.jpg/330px-LA2_Skultuna_kontorsljusstake.jpg','LA2','CC BY-SA 3.0'),
  ('air-freshener','thumb/f/f4/Febreze_air_fresheners.JPG/330px-Febreze_air_fresheners.JPG','KRoock74','CC BY-SA 3.0'),
  ('zip-ties','thumb/2/2f/Cable_ties.jpg/330px-Cable_ties.jpg','Silverxxx (talk) Original uploader was Silverxxx at en.wikip','CC BY-SA 3.0'),
  ('petroleum-jelly','thumb/3/33/White_Petrolatum1.jpg/330px-White_Petrolatum1.jpg','Kiyok','CC BY-SA 3.0'),
  ('razor-blades','thumb/9/9b/Quattro_Titanium_Energy.jpg/330px-Quattro_Titanium_Energy.jpg','Marcus Wengenroth','CC BY-SA 3.0'),
  ('shaving-cream','thumb/a/a3/Crema_para_afeitar.JPG/330px-Crema_para_afeitar.JPG','CoffeeAddict','CC BY 3.0'),
  ('aftershave','thumb/f/f3/Kent_shaving_brush.jpg/330px-Kent_shaving_brush.jpg','giammi','CC BY-SA 2.0'),
  ('electric-shaver','thumb/5/52/Philips_Norelco_9700_Rotary_Electric_Shaver_%2830973817280%29.jpg/330px-Philips_Norelco_9700_Rotary_Electric_Shaver_%2830973817280%29.jpg','moo.review','CC BY 2.0'),
  ('beard-oil','thumb/6/67/Beard_Oil_and_Brush.jpg/330px-Beard_Oil_and_Brush.jpg','Tools of Men','CC BY 2.0'),
  ('tampons','thumb/f/f8/Gestion_menstrual_tampon_toallitas_menstruaci%C3%B3n_periodicas_06.jpg/330px-Gestion_menstrual_tampon_toallitas_menstruaci%C3%B3n_periodicas_06.jpg','TitiNicola','CC BY-SA 4.0'),
  ('menstrual-pads','thumb/b/b8/Sanitary_towel.jpg/330px-Sanitary_towel.jpg','Wikimedia Commons','CC BY-SA 3.0'),
  ('menstrual-cup','thumb/b/b8/%D0%9C%D0%B5%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D1%81%D0%BA_%D0%B8_%D0%BC%D0%B5%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%87%D0%B0%D1%88%D0%B0_%28cropped%29.jpg/330px-%D0%9C%D0%B5%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D1%8B%D0%B9_%D0%B4%D0%B8%D1%81%D0%BA_%D0%B8_%D0%BC%D0%B5%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0%D1%8F_%D1%87%D0%B0%D1%88%D0%B0_%28cropped%29.jpg','Witchox','CC BY-SA 4.0'),
  ('period-underwear','thumb/c/c8/Menstrual_underwear_period_underwear_1.jpg/330px-Menstrual_underwear_period_underwear_1.jpg','Vulvani','CC BY-SA 4.0'),
  ('cold-medicine','thumb/7/76/Cough_medicine.jpg/330px-Cough_medicine.jpg','Mysid','Public domain'),
  ('throat-lozenges','thumb/b/b8/Hustenbonbon.JPG/330px-Hustenbonbon.JPG','Thogru','CC BY-SA 3.0'),
  ('antacid','thumb/5/57/Antacid-L478.jpg/330px-Antacid-L478.jpg','Midnightcomm','CC BY 2.5'),
  ('antiseptic','thumb/c/ca/Peroxid_vod%C3%ADku.jpg/330px-Peroxid_vod%C3%ADku.jpg','Wesalius','CC BY-SA 4.0'),
  ('thermometer','thumb/5/57/Mercury_Thermometer.jpg/330px-Mercury_Thermometer.jpg','Anonimski','CC BY-SA 3.0'),
  ('multivitamin','thumb/6/66/B_vitamin_supplement_tablets.jpg/330px-B_vitamin_supplement_tablets.jpg','Ragesoss','CC BY-SA 3.0'),
  ('probiotics','thumb/1/17/Yogurt%2C_Samoa%2C_Yoggi_original.JPG/330px-Yogurt%2C_Samoa%2C_Yoggi_original.JPG','Jin Zan','CC BY-SA 4.0'),
  ('eye-drops','thumb/7/77/Eye_drop.jpg/330px-Eye_drop.jpg','"Applying Eye Drops" by National Eye Institute (licensed und','CC BY 2.0'),
  ('diapers','thumb/d/d8/Disposablediaper.JPG/330px-Disposablediaper.JPG','Coop41','Public domain'),
  ('baby-wipes','thumb/b/b0/Erfrischungstuch.jpg/330px-Erfrischungstuch.jpg','joho345','CC BY-SA 3.0'),
  ('infant-formula','thumb/2/29/Infant_formula.jpg/330px-Infant_formula.jpg','국립국어원','CC BY-SA 2.0 kr'),
  ('toddler-formula','thumb/2/29/Infant_formula.jpg/330px-Infant_formula.jpg','국립국어원','CC BY-SA 2.0 kr'),
  ('baby-shampoo','thumb/a/ad/Baby_Shampoo_%2850841206943%29.jpg/330px-Baby_Shampoo_%2850841206943%29.jpg','ajay_suresh','CC BY 2.0')
) as v(id, path, attribution, license)
where p.id = v.id and p.image_url is null;
